#TITLE=webtip
#INFO
New Cliptext library
#SORT=y

#T=!
!important
#T=!--
<!-- ^! -->
#T=!doctype
<!doctype html>
#T=@f
@font-face {font-family:^!;src:url();}
#T=@i
@import url(^!);
#T=@m
@media print {^!}
#T=a
<a href="#">^!</a>
#T=abbr
<abbr>^!</abbr>
#T=abort
abort(^!)
#T=abs
abs(^!)
#T=acos
acos(^!)
#T=add
add(^!)
#T=addBehavior
addBehavior(^!)
#T=addClass
addClass(^!)
#T=addImport
addImport(^!)
#T=addPageRule
addPageRule(^!)
#T=addReadRequest
addReadRequest(^!)
#T=address
<address>^!</address>
#T=addRule
addRule(^!)
#T=a-email
<a href="mailto:^!">
#T=after
after(^!)
#T=afunc
function (^!) {
}
#T=ajax
$.ajax({
    type: "POST",
    url: "test.html",
    data: getdata,
    dataType: 'json',
    success: function(data){
    },
    error:function  () {
    },
    beforeSend:function  () {
        alert('1212');
    }
});
#T=ajaxComplete
ajaxComplete(function(event, request, settings){
    ^!
})
#T=ajaxError
ajaxError(function(event, request, settings){
    ^!
})
#T=ajaxSend
ajaxSend(function(event, request, settings){
    ^!
})
#T=ajaxStart
ajaxStart(function(^!){
})
#T=ajaxStop
ajaxStop(function(^!){
})
#T=ajaxSuccess
ajaxSuccess(function(event, request, settings){
    ^!
})
#T=alert
alert('111222');
#T=anchor
anchor(^!)
#T=andSelf
andSelf()^!
#T=animate
animate(^!)
#T=append
append(^!)
#T=appendChild
appendChild(^!)
#T=appendData
appendData(^!)
#T=appendTo
appendTo(^!)
#T=apply
apply(^!)
#T=applyElement
applyElement(^!)
#T=area
<area shape="^!" href="" coords="" alt="" />
#T=arguments
arguments
#T=article
<article>^!<article>
#T=aside
<aside>^!</aside>
#T=asin
asin(^!)
#T=assign
assign(^!)
#T=atan
atan(^!)
#T=atan2
atan2(^!)
#T=attachEvent
attachEvent(^!)
#T=attr
attr(^!)
#T=audio
<audio src="^!"></audio>
#T=b
^^
  ^!

#T=b-a
bottom:auto;
#T=back
back(^!)
#T=base
<base href="^!" />
#T=bd
border:^!;
#T=bd-
border:1px solid #000;
#T=bdb
border-bottom:^!;
#T=bdb-
border-bottom:1px solid #000;
#T=bdbc
border-bottom-color:#000;
#T=bdbi
border-bottom-image:url(^!);
#T=bdbi-n
border-bottom-image:none;
#T=bdbk
border-break:^!;
#T=bdbk-c
border-break:close;
#T=bdbli
border-bottom-left-image:url(^!);
#T=bdbli-c
border-bottom-left-image:continue;
#T=bdbli-n
border-bottom-left-image:none;
#T=bdblrs
border-bottom-left-radius:^!;
#T=bdb-n
border-bottom:none;
#T=bdbri
border-bottom-right-image:url(^!);
#T=bdbri-c
border-bottom-right-image:continue;
#T=bdbri-n
border-bottom-right-image:none;
#T=bdbrrs
border-bottom-right-radius:^!;
#T=bdbs
border-bottom-style:^!;
#T=bdbs-n
border-bottom-style:none;
#T=bdbw
border-bottom-width:^!;
#T=bdc
border-color:#000;
#T=bdci
border-corner-image:url(^!);
#T=bdci-c
border-corner-image:continue;
#T=bdci-n
border-corner-image:none;
#T=bdcl
border-collapse:^!;
#T=bdcl-c
border-collapse:collapse;
#T=bdcl-s
border-collapse:separate;
#T=bdf
border-fit:^!;
#T=bdf-c
border-fit:clip;
#T=bdf-of
border-fit:overflow;
#T=bdf-ow
border-fit:overwrite;
#T=bdf-r
border-fit:repeat;
#T=bdf-sc
border-fit:scale;
#T=bdf-sp
border-fit:space;
#T=bdf-st
border-fit:stretch;
#T=bdi
border-image:url(^!);
#T=bdi-m
-moz-border-image:url(^!) 0 0 0 0 stretch stretch;
#T=bdi-n
border-image:none;
#T=bdi-w
-webkit-border-image:url(^!) 0 0 0 0 stretch stretch;
#T=bdl
border-length:^!;
#T=bdl
border-left:^!;
#T=bdl-
border-left:1px solid #000;
#T=bdl-a
border-length:auto;
#T=bdlc
border-left-color:#000;
#T=bdli
border-left-image:url(^!);
#T=bdli-n
border-left-image:none;
#T=bdl-n
border-left:none;
#T=bdls
border-left-style:^!;
#T=bdls-n
border-left-style:none;
#T=bdlw
border-left-width:^!;
#T=bd-n
border:none;
#T=bdo
<bdo dir="rtl">^!</bdo>
#T=bdr
border-right:^!;
#T=bdr-
border-right:1px solid #000;
#T=bdra
border-radius:^!;
#T=bdrc
border-right-color:#000;
#T=bdri
border-right-image:url(^!);
#T=bdri-n
border-right-image:none;
#T=bdr-n
border-right:none;
#T=bdrs
border-right-style:^!;
#T=bdrs-n
border-right-style:none;
#T=bdrw
border-right-width:^!;
#T=bds
border-style:^!;
#T=bds-db
border-style:double;
#T=bds-ds
border-style:dashed;
#T=bds-dt
border-style:dotted;
#T=bds-dtds
border-style:dot-dash;
#T=bds-dtdtds
border-style:dot-dot-dash;
#T=bds-g
border-style:groove;
#T=bds-h
border-style:hidden;
#T=bds-i
border-style:inset;
#T=bds-n
border-style:none;
#T=bds-o
border-style:outset;
#T=bdsp
border-spacing:^!;
#T=bds-r
border-style:ridge;
#T=bds-s
border-style:solid;
#T=bds-w
border-style:wave;
#T=bdt
border-top:^!;
#T=bdt-
border-top:1px solid #000;
#T=bdtc
border-top-color:#000;
#T=bdti
border-top-image:url(^!);
#T=bdti-n
border-top-image:none;
#T=bdtli
border-top-left-image:url(^!);
#T=bdtli-c
border-top-left-image:continue;
#T=bdtli-n
border-top-left-image:none;
#T=bdtlrs
border-top-left-radius:^!;
#T=bdt-n
border-top:none;
#T=bdtri
border-top-right-image:url(^!);
#T=bdtri-c
border-top-right-image:continue;
#T=bdtri-n
border-top-right-image:none;
#T=bdtrrs
border-top-right-radius:^!;
#T=bdts
border-top-style:^!;
#T=bdts-n
border-top-style:none;
#T=bdtw
border-top-width:^!;
#T=bdw
border-width:^!;
#T=before
before(^!)
#T=bg
background:^!;
#T=bg-
background:url("^!") 0 0 no-repeat;
#T=bga
background-attachment:^!;
#T=bga-f
background-attachment:fixed;
#T=bga-s
background-attachment:scroll;
#T=bgbk
background-break:^!;
#T=bgbk-bb
background-break:bounding-box;
#T=bgbk-c
background-break:continuous;
#T=bgbk-eb
background-break:each-box;
#T=bgc
background-color:#FFF;
#T=bgcp
background-clip:^!;
#T=bgcp-bb
background-clip:border-box;
#T=bgcp-cb
background-clip:content-box;
#T=bgcp-nc
background-clip:no-clip;
#T=bgcp-pb
background-clip:padding-box;
#T=bgi
background-image:url(^!);
#T=bg-ie
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='${1:x}.png'sizingMethod='${2:crop}');
#T=bgi-n
background-image:none;
#T=bg-n
background:none;
#T=bgo
background-origin:^!;
#T=bgo-bb
background-origin:border-box;
#T=bgo-cb
background-origin:content-box;
#T=bgo-pb
background-origin:padding-box;
#T=bgp
background-position:0 0;
#T=bgpx
background-position-x:^!;
#T=bgpy
background-position-y:^!;
#T=bgr
background-repeat:^!;
#T=bgr-n
background-repeat:no-repeat;
#T=bgr-x
background-repeat:repeat-x;
#T=bgr-y
background-repeat:repeat-y;
#T=bgs-
background-size:auto auto;
#T=bgtr
background: transparent;
#T=bgz
background-size:^!;
#T=bgz-a
background-size:auto;
#T=bgz-ct
background-size:contain;
#T=bgz-cv
background-size:cover;
#T=big
big(^!)
#T=bind
bind(^!)
#T=blockquote
<blockquote>^!</blockquote>
#T=blur
blur(^!)
#T=body
<body>^!</body>
#T=bold
bold(^!)
#T=bool
var /*bool*/ 
#T=bottom
bottom:^!;
#T=bp-j
-webkit-box-pack: justify;
#T=br
<br />
#T=bubbleEvent
bubbleEvent(^!)
#T=button
<button type="button">^!</button>
#T=bxsh
box-shadow:^!;
#T=bxsh-n
box-shadow:none;
#T=bxz
box-sizing:^!;
#T=bxz-bb
box-sizing:border-box;
#T=bxz-cb
box-sizing:content-box;
#T=c
color:#000;
#T=caarc
arc(this.pos.x,this.pos.y,this.size,0,Math.PI*2,true);
#T=cabp
beginPath();
#T=cacp
closePath();
#T=cacr
clearRect(0, 0, c.width, c.height);
#T=cadi
drawImage(img_link, 0, 0);
this.ctx.drawImage('images/moon.png', 150, 150);
#T=caf
fill();
#T=caft
fillStyle();
#T=cagco-l
globalCompositeOperation = 'lighter'
#T=calc-b
lineCap = 'butt';
#T=calc-r
lineCap = 'round';
#T=calc-s
lineCap = 'square';
#T=call
call(^!)
#T=canvas
<canvas>^!</canvas>
#T=cap
(Math.PI/180)*270
#T=caption
<caption>^!</caption>
#T=cas
stroke();
#T=case
case ^!:
#T=cass
strokeStyle
#T=catch
catch (^!) {
}
#T=catran
translate(0,0);
#T=cc-ie
<!--[if IE]>
  ^!		
<![endif]-->
#T=cc-ie6
<!--[if lte IE 6]>
  ^!	
<![endif]-->
#T=cc-noie
<!--[if !IE]><!-->
  ^!		
<!--<![endif]-->
#T=ceil
ceil(^!)
#T=center
center
#T=change
change(^!)
#T=charAt
charAt(^!)
#T=charCodeAt
charCodeAt(^!)
#T=childrenj
children(^!)
#T=cite
<cite>^!</cite>
#T=cl
clear:^!;
#T=class
class="^!"
#T=cl-b
clear:both;
#T=clear
clear(^!)
#T=clearAttributes
clearAttributes(^!)
#T=clearData
clearData(^!)
#T=clearInterval
clearInterval(^!)
#T=clearQueue
clearQueue(^!)
#T=clearRequest
clearRequest(^!)
#T=clearTimeout
clearTimeout(^!)
#T=click
click(^!)
#T=cl-l
clear:left;
#T=cl-n
clear:none;
#T=clone
clone(^!)
#T=cloneall
clone(true)^!
#T=cloneNode
cloneNode(^!)
#T=close
close(^!)
#T=closest
closest(^!)
#T=cl-r
clear:right;
#T=code
<code>^!</code>
#T=coi
counter-increment:^!;
#T=col
<col>^!</col>
#T=colgroup
<colgroup>^!</colgroup>
#T=collapse
collapse(^!)
#T=colspan
colspan="^!"
#T=command
<command>^!</command>
#T=compareEndPoints
compareEndPoints(^!)
#T=compile
compile(^!)
#T=componentFromPoint
componentFromPoint(^!)
#T=concat
concat(^!)
#T=confirm
confirm(^!)
#T=console.log
console.log(^!);
#T=container
container
#T=contains
contains(^!)
#T=contenteditable html5 文本框编辑
contenteditable="true"
#T=contents
contents()^!
#T=context
context(^!)
#T=continue
continue
#T=controlRange
controlRange(^!)
#T=cor
counter-reset:^!;
#T=cos
cos(^!)
#T=cp
clip:^!;
#T=cp-a
clip:auto;
#T=cp-r
clip:rect(^!);
#T=cps
caption-side:^!;
#T=cps-b
caption-side:bottom;
#T=cps-t
caption-side:top;
#T=createAttribute
createAttribute(^!)
#T=createCaption
createCaption(^!)
#T=createComment
createComment(^!)
#T=createControlRange
createControlRange(^!)
#T=createDocumentFragment
createDocumentFragment(^!)
#T=createElement
createElement(^!)
#T=createEventObject
createEventObject(^!)
#T=createPopup
createPopup(^!)
#T=createRange
createRange(^!)
#T=createRangeCollection
createRangeCollection(^!)
#T=createStyleSheet
createStyleSheet(^!)
#T=createTextNode
createTextNode(^!)
#T=createTextRange
createTextRange(^!)
#T=createTFoot
createTFoot(^!)
#T=createTHead
createTHead(^!)
#T=css
css(^!)
#T=ct
content:^!;
#T=ct-a
content:attr(^!);
#T=ct-c
content:counter(^!);
#T=ct-cq
content:close-quote;
#T=ct-cs
content:counters(^!);
#T=ct-n
content:normal;
#T=ct-ncq
content:no-close-quote;
#T=ct-noq
content:no-open-quote;
#T=ct-oq
content:open-quote;
#T=cur
cursor:^!;
#T=cur-a
cursor:auto;
#T=cur-c
cursor:crosshair;
#T=cur-d
cursor:default;
#T=cur-ha
cursor:hand;
#T=cur-he
cursor:help;
#T=cur-m
cursor:move;
#T=cur-p
cursor:pointer;
#T=cur-t
cursor:text;
#T=d
'^!'
#T=data
data(^!)
#T=data-form="select"
/*-- 表单select --*/
+function ($) {
  'use strict';

}(jQuery); 
#T=datalist
<datalist>
  <option value="^!"></option>
  <option value=""></option>
</datalist>
#T=d-b
display:block;
#T=dblclick
dblclick(^!)
#T=d-cp
display:compact;
#T=dd
<dd>^!</dd>
#T=decodeURI
decodeURI(^!)
#T=decodeURIComponent
decodeURIComponent(^!)
#T=default
default
#T=del
<del>^!</del>
#T=delay
delay(^!)
#T=delegate
delegate(^!)
#T=deleteCaption
deleteCaption(^!)
#T=deleteCell
deleteCell(^!)
#T=deleteData
deleteData(^!)
#T=deleteRow
deleteRow(^!)
#T=deleteTFoot
deleteTFoot(^!)
#T=deleteTHead
deleteTHead(^!)
#T=dequeue
dequeue(^!)
#T=detach
detach(^!)
#T=detachEvent
detachEvent(^!)
#T=details
<details>^!</details>
#T=d-fl
display:flex;
#T=dfn
<dfn>^!</dfn>
#T=d-i
display:inline;
#T=d-ib
display:inline-block;
#T=die
die(^!)
#T=display
display:^!;
#T=d-itb
display:inline-table;
#T=div
<div>^!</div>
#T=dl
<dl>
  <dt>^!</dt>
  <dd></dd>
</dl>
#T=d-li
display:list-item;
#T=d-n
display:none;
#T=do
do {
} while (^!);
#T=d-rb
display:ruby;
#T=d-rbb
display:ruby-base;
#T=d-rbbg
display:ruby-base-group;
#T=d-rbt
display:ruby-text;
#T=d-rbtg
display:ruby-text-group;
#T=d-ready
$(document).ready(function() {
  ^!	
})
#T=d-ri
display:run-in;
#T=dt
<dt>^!</dt>
#T=d-tb
display:table;
#T=d-tbc
display:table-cell;
#T=d-tbcl
display:table-column;
#T=d-tbclg
display:table-column-group;
#T=d-tbcp
display:table-caption;
#T=d-tbfg
display:table-footer-group;
#T=d-tbhg
display:table-header-group;
#T=d-tbr
display:table-row;
#T=d-tbrg
display:table-row-group;
#T=each
each(function () {
    ^!
})
#T=ec
empty-cells:^!;
#T=ec-h
empty-cells:hide;
#T=ec-s
empty-cells:show;
#T=elementFromPoint
elementFromPoint(^!)
#T=else
else {
  ^!
}
#T=elseif
else if (^!) {
}
#T=em
<em>^!</em>
#T=embed
<embed src="^!" quality="high" type="application/x-shockwave-flash"></embed>
#T=empty
empty(^!)
#T=encodeURI
encodeURI(^!)
#T=encodeURIComponent
encodeURIComponent(^!)
#T=end
end()^!
#T=eq
eq(^!)
#T=error
error(^!)
#T=escape
escape(^!)
#T=eval
eval(^!)
#T=exec
exec(^!)
#T=execCommand
execCommand(^!)
#T=exp
exp(^!)
#T=f
font:^!;
#T=f-
font:1em Arialsans-serif;
#T=f10
font-size:0.833em;
#T=f11
font-size:0.917em;
#T=f13
font-size:1.083em;
#T=f14
font-size:1.167em;
#T=f15
font-size:1.25em;
#T=f16
font-size:1.333em;
#T=f17
font-size:1.417em;
#T=f18
font-size:1.5em;
#T=f19
font-size:1.583em;
#T=f20
font-size:1.667em;
#T=fadein
fadeIn(^!)
#T=fadeout
fadeOut(^!)
#T=fadeto
fadeTo(^!)
#T=ff
font-family:^!;
#T=ff-c
font-family:cursive;
#T=ff-f
font-family:fantasy;
#T=ff-m
font-family:monospace;
#T=ff-s
font-family:serif;
#T=ff-ss
font-family:sans-serif;
#T=ff-st
font-family:'\5B8B\4F53',Arial;
#T=ff-yh
font-family:'微软雅黑';
#T=fieldset
<fieldset>
  <legend>^!</legend>
  <details></details>
</fieldset>
#T=figcaption
<figcaption>^!</figcaption>
#T=figure
<figure>
  <img src="" alt="" />
  <figcaption>^!</figcaption>
</figure>
#T=filter
filter(^!)
#T=find
find(^!)
#T=findText
findText(^!)
#T=fireEvent
fireEvent(^!)
#T=first
first()^!
#T=first-c
first-child
#T=firstPage
firstPage(^!)
#T=fixed
fixed(^!)
#T=fl
float:^!;
#T=flash自适应
    <div class="wrap">
      <div class="flash">
          <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,19,0" width="1440" height="774">
           <param name="movie" value="index.swf">
           <param name="quality" value="high">
           <param name="wmode" value="transparent">
           <embed src="index.swf" quality="high" wmode="transparent" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" width="1440" height="774"></embed>
        </object>
      </div>
    </div>


<script type="text/javascript">
    function resizefalsh(obj,min,max) {
    var windw = $(window).width();
    var windh = $(window).height();
    
    if (windw < min.w) {
      obj.width(min.w);
    }else {
      if (windw > max.w) {
        obj.width(max.w);
      }else {
        obj.width(windw);
      }
    }
    
    if (windh < min.h) {
      obj.height(min.h);
    }else {
      if (windh > max.h) {
        obj.height(max.h);
      }else {
        obj.height(windh);
      }
    }
  }

  resizefalsh($(".flashwrap"),{'w':1150,'h':678},{'w':1680,'h':890});

  $(window).resize(function(){
    resizefalsh($(".flashwrap"),{'w':1150,'h':678},{'w':1680,'h':890});
  })
</script>

#T=fl-l
float:left;
#T=fl-n
float:none;
#T=floor
floor(^!)
#T=fl-r
float:right;
#T=focus
focus(^!)
#T=fontcolor
fontcolor(^!)
#T=fontsize
fontsize(^!)
#T=footer
<footer>^!</footer>
#T=for
for (var i = 0;  i< ^!; i++) {
}
#T=forin
for (var i in ^!) {
}
#T=forl
for (var i = 0, l = ^!.length; i < l; ++i) {
}
#T=form-get
<form  method="get" action="">
    ^!		
</form>
#T=form-post
<form method="post" action="">
    ^!
</form>
#T=forward
forward(^!)
#T=fromCharCode
fromCharCode(^!)
#T=fs
font-size:^!;
#T=fs-i
font-style:italic;
#T=fsm
font-smooth:^!;
#T=fsm-a
font-smooth:auto;
#T=fsm-aw
font-smooth:always;
#T=fsm-n
font-smooth:never;
#T=fs-n
font-style:normal;
#T=fs-o
font-style:oblique;
#T=fst
font-stretch:^!;
#T=fst-c
font-stretch:condensed;
#T=fst-e
font-stretch:expanded;
#T=fst-ec
font-stretch:extra-condensed;
#T=fst-ee
font-stretch:extra-expanded;
#T=fst-n
font-stretch:normal;
#T=fst-sc
font-stretch:semi-condensed;
#T=fst-se
font-stretch:semi-expanded;
#T=fst-uc
font-stretch:ultra-condensed;
#T=fst-ue
font-stretch:ultra-expanded;
#T=fsy
font-style:^!;
#T=func
function ^! () {
}
#T=funci
function(){
    ^!
}
#T=function
function ^! () {
}
#T=fv
font-variant:^!;
#T=fv-n
font-variant:normal;
#T=fv-sc
font-variant:small-caps;
#T=fw
font-weight:^!;
#T=fw-b
font-weight:bold;
#T=fw-br
font-weight:bolder;
#T=fw-lr
font-weight:lighter;
#T=fw-n
font-weight:normal;
#T=fz
font-size:^!;
#T=fza
font-size-adjust:^!;
#T=fza-n
font-size-adjust:none;
#T=get
get(^!)
#T=getAdjacentText
getAdjacentText(^!)
#T=getAllResponseHeaders
getAllResponseHeaders(^!)
#T=getAttribute
getAttribute(^!)
#T=getAttributeNode
getAttributeNode(^!)
#T=getBookmark
getBookmark(^!)
#T=getBoundingClientRect
getBoundingClientRect(^!)
#T=getCharset
getCharset(^!)
#T=getClientRects
getClientRects(^!)
#T=getDate
getDate(^!)
#T=getDay
getDay(^!)
#T=getElementById
getElementById(^!)
#T=getElementsByName
getElementsByName(^!)
#T=getElementsByTagName
getElementsByTagName(^!)
#T=getExpression
getExpression(^!)
#T=getFullYear
getFullYear(^!)
#T=getHours
getHours(^!)
#T=getItem
getItem(^!)
#T=getMilliseconds
getMilliseconds(^!)
#T=getMinutes
getMinutes(^!)
#T=getMonth
getMonth(^!)
#T=getNamedItem
getNamedItem(^!)
#T=GetObject
GetObject(^!)
#T=getResponseHeader
getResponseHeader(^!)
#T=getSeconds
getSeconds(^!)
#T=getTime
getTime(^!)
#T=getTimezoneOffset
getTimezoneOffset(^!)
#T=getUTCDate
getUTCDate(^!)
#T=getUTCDay
getUTCDay(^!)
#T=getUTCFullYear
getUTCFullYear(^!)
#T=getUTCHours
getUTCHours(^!)
#T=getUTCMilliseconds
getUTCMilliseconds(^!)
#T=getUTCMinutes
getUTCMinutes(^!)
#T=getUTCMonth
getUTCMonth(^!)
#T=getUTCSeconds
getUTCSeconds(^!)
#T=getVarDate
getVarDate(^!)
#T=getYear
getYear(^!)
#T=go
go(^!)
#T=h
height:^!;
#T=h1
<h1>^!</h1>
#T=h2
<h2>^!</h2>
#T=h3
<h3>^!</h3>
#T=h4
<h4>^!</h4>
#T=h5
<h5>^!</h5>
#T=h6
<h6>^!</h6>
#T=h-a
height:auto;
#T=has
has(^!)
#T=hasAttribute
hasAttribute(^!)
#T=hasChildNodes
hasChildNodes(^!)
#T=hasClass
hasClass(^!)
#T=hasFeature
hasFeature(^!)
#T=hasFocus
hasFocus(^!)
#T=hasOwnProperty
hasOwnProperty(^!)
#T=head
<head>^!</head>
#T=header
<header>^!</header>
#T=height
height="^!"
#T=heightj
height(^!)
#T=hgroup
<hgroup>^!</hgroup>
#T=hide
hide(^!)
#T=hide
hide(^!)
#T=history-b
history.back();
#T=history-p
history.prev();
#T=hover
hover(^!)
#T=hr
<hr />^!
#T=href-j
href="javascript:void(0);"
#T=href-n
href="#"
#T=html
<html>^!</html>
#T=html()
html(^!)
#T=html5-ie
<!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
#T=html-form-inline
<!-- start form-inline -->
        <style type="text/css">
          .form-inline .form-group{display: inline-block; margin-bottom: 0; vertical-align: middle; _display:inline;}
          .form-inline .form-control {display:inline-block; height: 20px; padding: 6px 12px; font-size: 14px; line-height: 1.428571429; color: #555; vertical-align: middle; background-color: #fff; background-image: none; border: 1px solid #ccc; border-radius: 4px;}
          .form-inline .sr-only {position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); border: 0;}
          .form-inline .radio, .form-inline .checkbox { display: inline-block; padding-left: 0; margin-top: 0; margin-bottom: 0; _display:inline; }
          .form-inline .checkbox input,.form-inline .radio input{position:relative;top:2px;}
          .form-inline .btn {display: inline-block;  padding: 6px 12px; margin-bottom: 0; font-size: 14px; font-weight: normal; line-height: 1.428571429; text-align: center; white-space: nowrap; vertical-align: middle;}
        </style>
        <form class="form-inline" >
            <div class="form-group">
              <label class="sr-only" for="exampleInputEmail2">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail2" placeholder="Enter email">
            </div>
            <div class="form-group">
              <label class="sr-only" for="exampleInputPassword2">Password</label>
              <input type="password" class="form-control" id="exampleInputPassword2" placeholder="Password">
            </div>
            <div class="checkbox">
              <label>
              <input type="checkbox"> Remember me
              </label>
          </div>
          <div class="radio">
              <label>
              <input type="radio"> Remember me
              </label>
          </div>
            <button type="submit" class="btn btn-default">Sign in</button>
        </form>
        <!-- end form-inline -->
#T=html-form-v
        <!-- start form-v -->
        <style type="text/css">
          .form-v {font-size:14px;}
          .form-v .form-group {margin-bottom:15px;}
          .form-v .form-group label {display:inline-block;margin-bottom:5px; font-weight:bold;}
          .form-v .form-control,.form-v .file{display:block;width:100%;height: 20px; padding: 6px 12px; font-size: 14px; line-height: 1.428571429; color: #555; vertical-align: middle; background-color: #fff; background-image: none; border: 1px solid #ccc; border-radius: 4px;}
          .form-v .file {border:0;padding:0;}
          .form-v .help-block { display: block; margin-top: 5px; margin-bottom: 10px; color: #737373; line-height:2;}
          .form-v .checkbox,.form-v .radio {display: block; min-height: 20px;  margin-top: 10px; margin-bottom: 10px; vertical-align: middle;}
          .form-v .checkbox input,.form-v .radio input{ line-height: normal;padding: 0; box-sizing: border-box; float:left; margin-right:5px;}
          .form-v .btn {display: inline-block; padding: 6px 12px; margin-bottom: 0; font-size: 14px; font-weight: normal; line-height: 1.428571429; text-align: center; white-space: nowrap; vertical-align: middle;}
        </style>
        <form action="#" class="form-v">
          <div class="form-group">
          <label for="exampleInputEmail1">Email address</label>
          <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
          </div>
          <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
          </div>
          <div class="form-group">
          <label for="exampleInputFile">File input</label>
          <input class="file" type="file" id="exampleInputFile">
          <p class="help-block">Example block-level help text here.</p>
          </div>
          <div class="checkbox">
          <label>
            <input type="checkbox"> Check me out
          </label>
          </div>
          <div class="radio">
          <label>
            <input type="radio"> Check me out
          </label>
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
        <!-- end form-ver -->
#T=html-note-ie6
<!--[if lte IE 6]>

<div style='border: 1px solid #F7941D; background: #FEEFDA; text-align: center; clear: both; height: 75px; position: relative;'>

<div style='width: 640px; margin: 0 auto; text-align: left; padding: 0; overflow: hidden; color: black;'>
<div style='width: 75px; float: left;'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-warning.jpg ' alt='Warning!'/></div>
<div style='width: 275px; float: left; font-family: Arial, sans-serif;'>
<div style='font-size: 14px; font-weight: bold; margin-top: 12px;'>发现你的浏览器(IE6)需要升级</div>
<div style='font-size: 12px; margin-top: 6px; line-height: 12px;'>为达最佳呈现效果,请升级至最新式浏览器.</div>
</div>

<div style='width: 75px; float: left;'><a href='http://www.firefox.com ' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-firefox.jpg ' style='border: none;' alt='Get Firefox 3.5'/></a></div>
<div style='width: 75px; float: left;'><a href='http://www.browserforthebetter.com/download.html ' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-ie8.jpg ' style='border: none;' alt='Get Internet Explorer 8'/></a></div>
<div style='width: 73px; float: left;'><a href='http://www.apple.com/safari/download/ ' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-safari.jpg ' style='border: none;' alt='Get Safari 4'/></a></div>
<div style='float: left;'><a href='http://www.google.com/chrome ' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-chrome.jpg ' style='border: none;' alt='Get Google Chrome'/></a></div>
</div>
</div>
<![endif]-->

#T=html-table
<style type="text/css">
.table-bordered {border: 1px solid #ddd;border-collapse: collapse;border-left: 0;-webkit-border-radius: 4px;-moz-border-radius: 4px;border-radius: 4px;border-top:0;border-spacing: 0;}
.table-bordered td, .table-bordered th {padding: 8px;line-height: 20px;text-align: left;vertical-align: top;border: 1px solid #ddd;}
</style>
<!-- start table -->
<table class="table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Username</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan="2">1</td>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    <tr>
      <td>Mark</td>
      <td>Otto</td>
      <td>@TwBootstrap</td>
    </tr>
    <tr>
      <td>2</td>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <td>3</td>
      <td colspan="2">Larry the Bird</td>
      <td>@twitter</td>
    </tr>
  </tbody>
</table>
<!-- end table -->
#T=html-temp5
<!DOCTYPE html>
<html>
<head>
  <script type="text/javascript">
    function browserRedirect() {
      var sUserAgent = navigator.userAgent.toLowerCase();
      var bIsIpad = sUserAgent.match(/ipad/i) == "ipad";
      var bIsIphoneOs = sUserAgent.match(/iphone os/i) == "iphone os";
      var bIsMidp = sUserAgent.match(/midp/i) == "midp";
      var bIsUc7 = sUserAgent.match(/rv:1.2.3.4/i) == "rv:1.2.3.4";
      var bIsUc = sUserAgent.match(/ucweb/i) == "ucweb";
      var bIsAndroid = sUserAgent.match(/android/i) == "android";
      var bIsCE = sUserAgent.match(/windows ce/i) == "windows ce";
      var bIsWM = sUserAgent.match(/windows mobile/i) == "windows mobile";

      if (bIsIpad || bIsIphoneOs || bIsMidp || bIsUc7 || bIsUc || bIsAndroid || bIsCE || bIsWM) {
        window.location.href = './wap/';
      } else {
        //window.location = 'index.html';
      }
    }

    browserRedirect();
  </script>
  <script type="text/javascript">
  (function(){
    'use strict';
    var Fixmobile = function  () {
      this.viwep();
    }

    Fixmobile.width = 640;

    Fixmobile.prototype.viwep = function  (e) {
      var phoneWidth = parseInt(window.screen.width),
      phoneScale = phoneWidth/Fixmobile.width,
      ua = navigator.userAgent,
      headmate;
      if (/Android (\d+\.\d+)/.test(ua)){
        var version = parseFloat(RegExp.$1);
        // andriod 2.3
        if(version > 2.3){
          document.write('<meta name="viewport" content="width=' + Fixmobile.width + ', minimum-scale = ' + phoneScale + ', maximum-scale = '+phoneScale+', target-densitydpi=device-dpi">');
        // andriod 2.3以上
        }else{
          document.write('<meta name="viewport" content="width=' + Fixmobile.width + ', target-densitydpi=device-dpi">');
        }
        // 其他系统
      } else {
        document.write('<meta name="viewport" content="width=' + Fixmobile.width + ', user-scalable=no, target-densitydpi=device-dpi">');
      }
    }
    var newviewport = new Fixmobile();
  })();
  </script>

  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=Edge">
  <meta name="renderer" content="webkit">
  <meta name="description" content="">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <link rel="stylesheet" href="css/style.css">
  <title>website name</title>
</head>
<body class="yh">
  <noscript>
    <strong>你的浏览器似乎禁用了 JavaScript。</strong><br />您必须在浏览器中启用JavaScript才能使用本网站的功能。
  </noscript>
  <div class="container">
     
  </div>
  <script type="text/javascript" src="js/jquery.js"></script>
  <script type="text/javascript" src="js/script.js"></script>
</body>
</html>
#T=i
<i>^!</i>
#T=if
if (^!) {
}
#T=iframe
<iframe src="^!"></iframe>
#T=img
<img src="^!" alt="" />
#T=indexj
index(^!)
#T=indexOf
indexOf(^!)
#T=innerHeight
innerHeight()^!
#T=innerHTML
innerHTML
#T=innerWidth
innerWidth()^!
#T=input
<input type="^!" name="" />
#T=input-b
<input type="button" value="" />
#T=input-button
<input type="button" value="" />
#T=input-c
<input type="checkbox" name="" id="" />
#T=input-checkbox
<input type="checkbox" name="" id="" />
#T=input-color
<input type="color" name="" id="" />
#T=input-date
<input type="date" name="" id="" />
#T=input-datetime
<input type="datetime" name="" id="" />
#T=input-datetime-local
<input type="datetime-local" name="" id="" />
#T=input-email
<input type="email" name="" id="" />
#T=input-f
<input type="file" name="" id="" />
#T=input-file
<input type="file" name="" id="" />
#T=input-h
<input type="hidden" name="" />
#T=input-hidden
<input type="hidden" name="" />
#T=input-i
<input type="image" src="" alt="" />
#T=input-image
<input type="image" src="" alt="" />
#T=input-month
<input type="month" name="" id="" />
#T=input-number
<input type="number" name="" id="" />
#T=input-p
<input type="password" name="" id="" />
#T=input-password
<input type="password" name="" id="" />
#T=input-r
<input type="radio" name="" id="" />
#T=input-range
<input type="range" name="" id="" />
#T=input-reset
<input type="reset" value="" />
#T=input-s
<input type="submit" value="" />
#T=input-search
<input type="search" name="" id="" />
#T=input-submit
<input type="submit" value="" />
#T=input-t
<input type="text" name="" id="" />
#T=input-text
<input type="text" name="" id="" />
#T=input-time
<input type="time" name="" id="" />
#T=input-url
<input type="url" name="" id="" />
#T=input-week
<input type="week" name="" id="" />
#T=inRange
inRange(^!)
#T=ins
<ins>^!</ins>
#T=insertAdjacentElement
insertAdjacentElement(^!)
#T=insertAdjacentHTML
insertAdjacentHTML(^!)
#T=insertAdjacentText
insertAdjacentText(^!)
#T=insertAfter
insertAfter(^!)
#T=insertBefore
insertBefore(^!)
#T=insertBefore
insertBefore(^!)
#T=insertCell
insertCell(^!)
#T=insertData
insertData(^!)
#T=insertRow
insertRow(^!)
#T=int
var /*int*/ 
#T=isEqual
isEqual(^!)
#T=isFinite
isFinite(^!)
#T=isNaN
isNaN(^!)
#T=isPrototypeOf
isPrototypeOf(^!)
#T=italics
italics(^!)
#T=javaEnabled
javaEnabled(^!)
#T=javaScript commands
^!
#T=jfocusout
focusout(function(){^!})
#T=join
join(^!)
#T=jq
$(^!)
#T=jqextendz
/** 
* extend ^!
* 
* @package jquery
* @author xcld
*/
#T=jqextendzcode
/** 
* extend ^!
* 
* @package jquery
* @author xcld
*/
;(function($){  
    $.fn.extendname = function (options) {  
        var defualts = { vareven: "click" };  
        var opts = $.extend({}, defualts, options);  
        var obj = $(this);
    };  
})(jQuery);
#T=js
show()^!
#T=js-v
javascript:void(0);
#T=jtriggerHandler
triggerHandler(^!)
#T=justify
justify
#T=k
{^!}
#T=kbd
<kbd>^!</kbd>
#T=key
key(^!)
#T=keydown
keydown(^!)
#T=keygen
<keygen name="^!"></keygen>
#T=keypress
keypress(^!)
#T=keyup
keyup(^!)
#T=kk
"^!"
#T=kk
"^!"
#T=l
(^!)
#T=l-a
left:auto;
#T=label
<label for="">^!</label>
#T=last
last()^!
#T=last-c
last-child
#T=lastIndexOf
lastIndexOf(^!)
#T=lastPage
lastPage(^!)
#T=layerX
layerX
#T=layerY
layerY
#T=lbound
lbound(^!)
#T=left
left:^!;
#T=legend
<legend>^!</legend>
#T=lh
line-height:^!;
#T=li
<li>^!</li>
#T=link
link(^!)
#T=link-atom
<link rel="alternate" type="application/atom+xml" title="Atom" href="atom.xml" />
#T=link-css
<link rel="stylesheet" type="text/css" href="" media="all" />
#T=link-favicon
<link rel="shortcut icon" type="image/x-icon" href="^!favicon.ico" />
#T=link-print
<link rel="stylesheet" type="text/css" href="^!print.css" media="print" />
#T=link-rss
<link rel="alternate" type="application/rss+xml" title="RSS" href="^!rss.xml" />
#T=link-touch
<link rel="apple-touch-icon" href="^!favicon.png" />
#T=lis
list-style:^!;
#T=lisi
list-style-image:^!;
#T=lisi-n
list-style-image:none;
#T=lis-n
list-style:none;
#T=lisp
list-style-position:^!;
#T=lisp-i
list-style-position:inside;
#T=lisp-o
list-style-position:outside;
#T=list
list-style-type:^!;
#T=list-c
list-style-type:circle;
#T=list-d
list-style-type:disc;
#T=list-dc
list-style-type:decimal;
#T=list-dclz
list-style-type:decimal-leading-zero;
#T=listen
listen(^!)
#T=list-lr
list-style-type:lower-roman;
#T=list-n
list-style-type:none;
#T=list-s
list-style-type:square;
#T=list-ur
list-style-type:upper-roman;
#T=live
live(^!)
#T=ll
"^!"
#T=ll
'^!'
#T=load
load(^!)
#T=localeCompare
localeCompare(^!)
#T=log
log(^!)
#T=lorem
lorem
#T=lts
letter-spacing:^!;
#T=m
margin:^!;
#T=m-0
margin:0;
#T=m-2
margin:0 0;
#T=m-3
margin:0 0 0;
#T=m-4
margin:0 0 0 0;
#T=m-a
margin:auto;
#T=mah
max-height:^!;
#T=mah-n
max-height:none;
#T=map
<map id="^!">
  <area shape="" href="" coords="" alt="" />
</map>
#T=map
map(^!)
#T=mark
<mark>^!</mark>
#T=match
match(^!)
#T=maw
max-width:^!;
#T=maw-n
max-width:none;
#T=max
max(^!)
#T=mb
margin-bottom:^!;
#T=mb-a
margin-bottom:auto;
#T=menu
<menu>^!</menu>
#T=mergeAttributes
mergeAttributes(^!)
#T=meta-com
<meta http-equiv="X-UA-Compatible" content="IE=7" />
#T=meta-edge
<meta http-equiv="X-UA-Compatible" content="IE=edge">
#T=meta-moblie
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;" name="viewport" />
#T=meta-utf
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
#T=meter
<meter>^!</meter>
#T=mih
min-height:^!;
#T=min
min(^!)
#T=miw
min-width:^!;
#T=ml
margin-left:^!;
#T=ml-a
margin-left:auto;
#T=mousedown
mousedown(function(){^!})
#T=mouseenter
mouseenter
#T=mouseleave
mouseleave
#T=mousemove
mousemove(function(){^!})
#T=mouseout
mouseout(function(){^!})
#T=mouseover
mouseover(function(){^!})
#T=mouseup
mouseup(function(){^!})
#T=move
move(^!)
#T=moveBy
moveBy(^!)
#T=moveEnd
moveEnd(^!)
#T=moveFirst
moveFirst(^!)
#T=moveNext
moveNext(^!)
#T=moveRow
moveRow(^!)
#T=moveStart
moveStart(^!)
#T=moveTo
moveTo(^!)
#T=moveToBookmark
moveToBookmark(^!)
#T=moveToElementText
moveToElementText(^!)
#T=moveToPoint
moveToPoint(^!)
#T=mr
margin-right:^!;
#T=mr-a
margin-right:auto;
#T=msWriteProfilerMark
msWriteProfilerMark(^!)
#T=mt
margin-top:^!;
#T=mt-a
margin-top:auto;
#T=namedItem
namedItem(^!)
#T=namedRecordset
namedRecordset(^!)
#T=nav
<nav>^!</nav>
#T=navigate
navigate(^!)
#T=nd-serv
http.createServer(function  (req,res) {
  res.writeHead(200,{'Content-Type':'text-html'});
  console.log('work');
  res.end('<h1>HEllow!!</h1>');
  
})
#T=next
next(^!)
#T=nextAll
nextAll(^!)
#T=nextPage
nextPage(^!)
#T=nextUntil
nextUntil(^!)
#T=ng-controller
ng-controller
#T=ng-model
ng-model
#T=ng-repeat
ng-repeat
#T=noConflict
noConflict(^!)
#T=normalize
normalize(^!)
#T=noscript
<noscript>^!</noscript>
#T=not
not(^!)
#T=nth-
nth-child(5n)
#T=nth-last-child(-n+5)
nth-last-child(-n+5)
#T=o
outline:^!;
#T=object
<object type="^!" width="550" height="400"></object>
#T=oc
outline-color:#000;
#T=oc-i
outline-color:invert;
#T=offset
offset(^!)
#T=offsetLeft
offsetLeft
#T=offsetParent
offsetParent()^!
#T=offsetTop
offsetTop
#T=offsetX
offsetX
#T=offsetY
offsetY
#T=ol
<ol>
  <li>^!</li>
  <li></li>
</ol>
#T=on
on(^!)
#T=o-n
outline:none;
#T=one
one(^!)
#T=oo
outline-offset:^!;
#T=op
opacity:^!;
#T=open
open(^!)
#T=op-ie
filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
#T=op-ms
-ms-filter:'progid:DXImageTransform.Microsoft.Alpha(Opacity=100)';
#T=optgroup
<optgroup label="^!">
  <option><option>
  <option><option>
</optgroup>
#T=option
<option>^!</option>
#T=orp
orphans:^!;
#T=os
outline-style:^!;
#T=outerHeight
outerHeight(^!)
#T=outerHTML
outerHTML
#T=outerWidth
outerWidth(^!)
#T=output
<output>^!</output>
#T=ov
overflow:^!;
#T=ov-a
overflow:auto;
#T=ov-h
overflow:hidden;
#T=ovs
overflow-style:^!;
#T=ov-s
overflow:scroll;
#T=ovs-a
overflow-style:auto;
#T=ovs-m
overflow-style:move;
#T=ovs-mq
overflow-style:marquee;
#T=ovs-p
overflow-style:panner;
#T=ovs-s
overflow-style:scrollbar;
#T=ov-v
overflow:visible;
#T=ovx
overflow-x:^!;
#T=ovx-a
overflow-x:auto;
#T=ovx-h
overflow-x:hidden;
#T=ovx-s
overflow-x:scroll;
#T=ovx-v
overflow-x:visible;
#T=ovy
overflow-y:^!;
#T=ovy-a
overflow-y:auto;
#T=ovy-h
overflow-y:hidden;
#T=ovy-s
overflow-y:scroll;
#T=ovy-v
overflow-y:visible;
#T=ow
outline-width:^!;
#T=p
<p>^!</p>
#T=p-0
padding:0;
#T=p-2
padding:0 0;
#T=p-3
padding:0 0 0;
#T=p-4
padding:0 0 0 0;
#T=param
<param name="^!" value="" />
#T=parentElement
parentElement(^!)
#T=parentj
parent(^!)
#T=parentNode
parentNode
#T=parents
parents(^!)
#T=parentsUntil
parentsUntil(^!)
#T=parse
parse(^!)
#T=parseFloat
parseFloat(^!)
#T=parseInt
parseInt(^!)
#T=pasteHTML
pasteHTML(^!)
#T=pb
padding-bottom:^!;
#T=pd
padding:^!;
#T=pgba
page-break-after:^!;
#T=pgba-al
page-break-after:always;
#T=pgba-au
page-break-after:auto;
#T=pgba-l
page-break-after:left;
#T=pgba-r
page-break-after:right;
#T=pgbb
page-break-before:^!;
#T=pgbb-al
page-break-before:always;
#T=pgbb-au
page-break-before:auto;
#T=pgbb-l
page-break-before:left;
#T=pgbb-r
page-break-before:right;
#T=pgbi
page-break-inside:^!;
#T=pgbi-au
page-break-inside:auto;
#T=pgbi-av
page-break-inside:avoid;
#T=pl
padding-left:^!;
#T=placeholder
placeholder="^!"
#T=pop
pop(^!)
#T=pos
position:^!;
#T=pos-a
position:absolute;
#T=pos-f
position:fixed;
#T=position
position()^!
#T=pos-r
position:relative;
#T=pos-s
position:static;
#T=postMessage
postMessage(^!)
#T=pow
pow(^!)
#T=pr
padding-right:^!;
#T=pre
<pre>^!</pre>
#T=prepend
prepend(^!)
#T=prepend
prepend(^!)
#T=prependTo
prependTo(^!)
#T=prev
prev(^!)
#T=prevAll
prevAll(^!)
#T=preventDefault
preventDefault()
#T=previousPage
previousPage(^!)
#T=prevUntil
prevUntil(^!)
#T=pri
/*private*/ 
#T=print
print(^!)
#T=private
/*private*/ 
#T=pro
prototype
#T=progress
<progress>^!</progress>
#T=prompt
prompt(^!)
#T=pt
padding-top:^!;
#T=pub
/*public*/ 
#T=public
/*public*/ 
#T=push
push(^!)
#T=q
quotes:^!;
#T=q
<q>^!</q>
#T=q-en
quotes:'\201C' '\201D' '\2018' '\2019';
#T=q-n
quotes:none;
#T=q-ru
quotes:'\00AB' '\00BB' '\201E' '\201C';
#T=queryCommandEnabled
queryCommandEnabled(^!)
#T=queryCommandIndeterm
queryCommandIndeterm(^!)
#T=queryCommandState
queryCommandState(^!)
#T=queryCommandSupported
queryCommandSupported(^!)
#T=queryCommandValue
queryCommandValue(^!)
#T=querySelector
querySelector(^!)
#T=querySelectorAll
querySelectorAll(^!)
#T=queue
queue(^!)
#T=r
right:^!;
#T=r-a
right:auto;
#T=raiseEvent
raiseEvent(^!)
#T=random
random(^!)
#T=ready
ready(function(){^!})
#T=recalc
recalc(^!)
#T=refresh
refresh(^!)
#T=releaseCapture
releaseCapture(^!)
#T=reload
reload(^!)
#T=remove
remove(^!)
#T=remove
remove(^!)
#T=removeAttr
removeAttr(^!)
#T=removeAttribute
removeAttribute(^!)
#T=removeAttributeNode
removeAttributeNode(^!)
#T=removeBehavior
removeBehavior(^!)
#T=removeChild
removeChild(^!)
#T=removeClass
removeClass(^!)
#T=removeData
removeData(^!)
#T=removeExpression
removeExpression(^!)
#T=removeImport
removeImport(^!)
#T=removeItem
removeItem(^!)
#T=removeNamedItem
removeNamedItem(^!)
#T=removeNode
removeNode(^!)
#T=removeRule
removeRule(^!)
#T=replace
replace(^!)
#T=replaceAdjacentText
replaceAdjacentText(^!)
#T=replaceAll
replaceAll(^!)
#T=replaceChild
replaceChild(^!)
#T=replaceData
replaceData(^!)
#T=replaceNode
replaceNode(^!)
#T=replaceWith
replaceWith(^!)
#T=reset
reset(^!)
#T=resize
resize(function(){^!})
#T=resizeBy
resizeBy(^!)
#T=resizeTo
resizeTo(^!)
#T=ret
return ^!;
#T=reverse
reverse(^!)
#T=round
round(^!)
#T=rp
<rp>^!</rp>
#T=rt
<rt>^!</rt>
#T=ruby
<ruby>^!</ruby>
#T=rz
resize:^!;
#T=rz-b
resize:both;
#T=rz-h
resize:horizontal;
#T=rz-n
resize:none;
#T=rz-v
resize:vertical;
#T=samp
<samp>^!</samp>
#T=script
<script type="text/javascript">
  ^!
</script>
#T=ScriptEngine
ScriptEngine(^!)
#T=ScriptEngineBuildVersion
ScriptEngineBuildVersion(^!)
#T=ScriptEngineMajorVersion
ScriptEngineMajorVersion(^!)
#T=ScriptEngineMinorVersion
ScriptEngineMinorVersion(^!)
#T=script-jq
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
#T=script-src
<script type="text/javascript" src="^!"></script>
#T=scroll
scroll(function(){^!})
#T=scroll
scroll(^!)
#T=scrollBy
scrollBy(^!)
#T=scrollIntoView
scrollIntoView(^!)
#T=scrollLeft
scrollLeft(^!)
#T=scrollTo
scrollTo(^!)
#T=scrollTop
scrollTop(^!)
#T=search
search(^!)
#T=section
<section>^!</section>
#T=select
<select name="^!">
  <option></option>
  <option></option>
</select>
#T=select
select(^!)
#T=selectedIndex
selectedIndex




#T=send
send(^!)
#T=serialize
serialize()^!
#T=serializeArray
serializeArray()^!
#T=setActive
setActive(^!)
#T=setAttribute
setAttribute(^!)
#T=setAttributeNode
setAttributeNode(^!)
#T=setCapture
setCapture(^!)
#T=setContextMenu
setContextMenu(^!)
#T=setData
setData(^!)
#T=setDate
setDate(^!)
#T=setEndPoint
setEndPoint(^!)
#T=setExpression
setExpression(^!)
#T=setFullYear
setFullYear(^!)
#T=setHours
setHours(^!)
#T=setInterval
setInterval(
    function(){^!},speed
)
#T=setItem
setItem(^!)
#T=setMilliseconds
setMilliseconds(^!)
#T=setMinutes
setMinutes(^!)
#T=setMonth
setMonth(^!)
#T=setNamedItem
setNamedItem(^!)
#T=setRequestHeader
setRequestHeader(^!)
#T=setSeconds
setSeconds(^!)
#T=setTime
setTime(^!)
#T=setTimeout
setTimeout(
  function(){
    ^!
  }, speed)
#T=setUTCDate
setUTCDate(^!)
#T=setUTCFullYear
setUTCFullYear(^!)
#T=setUTCHours
setUTCHours(^!)
#T=setUTCMilliseconds
setUTCMilliseconds(^!)
#T=setUTCMinutes
setUTCMinutes(^!)
#T=setUTCMonth
setUTCMonth(^!)
#T=setUTCSeconds
setUTCSeconds(^!)
#T=setYear
setYear(^!)
#T=shift
shift(^!)
#T=show
show()^!
#T=show
show(^!)
#T=showHelp
showHelp(^!)
#T=showModalDialog
showModalDialog(^!)
#T=showModelessDialog
showModelessDialog(^!)
#T=siblings
siblings(^!)
#T=sin
sin(^!)
#T=sizej
size()^!
#T=slice
slice(^!)
#T=slice
slice(^!)
#T=slideDown
slideDown(^!)
#T=slideToggle
slideToggle(^!)
#T=slideUp
slideUp(^!)
#T=small
<small>^!</small>
#T=small
small(^!)
#T=sort
sort(^!)
#T=source
<source>^!</source>
#T=span
<span>^!</span>
#T=splice
splice(^!)
#T=split
split(^!)
#T=splitText
splitText(^!)
#T=sqrt
sqrt(^!)
#T=start
start(^!)
#T=stop
stop(^!)
#T=stop
stop(^!)
#T=stopPropagation
stopPropagation()
#T=strike
strike(^!)
#T=string
var /*string*/ ^!
#T=strong
<strong>^!</strong>
#T=style=""
style="^!"
#T=style-wrap
<style type="text/css">
  ^!	
</style>
#T=sub
<sub>^!</sub>
#T=sub
sub(^!)
#T=submit
submit(^!)
#T=submit
submit(^!)
#T=substr
substr(^!)
#T=substring
substring(^!)
#T=substringData
substringData(^!)
#T=summary
<summary>^!</summary>
#T=sup
<sup>^!</sup>
#T=sup
sup(^!)
#T=swapNode
swapNode(^!)
#T=switch
switch (^!) {
case 1:
break
case 2:
break
default:
}
#T=t
top:^!;
#T=ta
text-align:^!;
#T=t-a
top:auto;
#T=table
<table>
<tr>
  <td>^!</td>
  <td></td>
</tr>
</table>
#T=table
table(^!)
#T=ta-c
text-align:center;
#T=tagName
tagName
#T=tags
tags(^!)
#T=taintEnabled
taintEnabled(^!)
#T=tal
text-align-last:^!;
#T=ta-l
text-align:left;
#T=tal-a
text-align-last:auto;
#T=tal-c
text-align-last:center;
#T=tal-l
text-align-last:left;
#T=tal-r
text-align-last:right;
#T=tan
tan(^!)
#T=ta-r
text-align:right;
#T=target
target
#T=target-b
target="_blank"
#T=tarray
/*Array*/ 
#T=tbl
table-layout:^!;
#T=tbl-a
table-layout:auto;
#T=tbl-f
table-layout:fixed;
#T=tbody
<tbody>^!</tbody>
#T=tbool
/*bool*/ 
#T=tchar
/*char*/ 
#T=tclass
/* class */ 
#T=tconst
/*const*/ 
#T=tcss-bt1 (a > span || button > span > span)
/*-- button --*/
.input-bt {margin:0; padding:0; border:0; background:none; width:100px;}
.input-bt .bt1 {position:relative;}
.bt1 { background:url("../images/bt.png") 0 0 no-repeat; padding-left:5px; display:inline-block;text-decoration:none; line-height:41px; border:none; margin:0; padding:0;}
.bt1 span {background:url("../images/bt.png") right 0 no-repeat; display:block; text-align:center; position:relative; left:5px; padding-right:5px; color:#fff; text-decoration:none; width:100px; font-size:20px; font-family:'\5B8B\4F53',Arial; cursor:pointer;}
#T=tcss-cols2 (wrap-left,wrap-center)
/*-- col2 --*/
.wrap-left {float:left;width:210px; margin-right:20px;}
.wrap-center {float:left; width:600px;}
#T=tcss-cols3 (wrap-left,wrap-center,wrap-right)
/*-- col3 --*/
.wrap-left {float:left;width:210px; margin-right:20px;}
.wrap-center {float:left; width:480px; margin-right:10px;}
.wrap-right {float:left; width:210px;}
#T=tcss-footer-link (foot-link > a)
/*-- footer-link --*/
.foot-link {text-align:center;}
.foot-link a {padding:0 5px; text-decoration:none;}
#T=tcss-list (float ul > li > a)
/*-- list float --*/
.list-fl {width:auto;}
.list-fl li {float:left;  font-weight: 800;}
.list-fl li a {color:#219A44;text-decoration:none; display:block;margin:12px 20px 0 0; word-break:keep-all;}
.list-fl li span {}
#T=tcss-list (nofloat ul > li > a >span)
/*-- list nofloat --*/
.list-nofl{width:auto;}
.list-nofl li{background:url("") 0 0 no-repeat;}
.list-nofl li a {text-decoration:none; padding-left:10px; display:block; }
.list-nofl li a span {}
#T=td
text-decoration:^!;
#T=td
<td>^!</td>
#T=tdate
/*Date*/ 
#T=tdic
/*Dictionary*/ 
#T=td-l
text-decoration:line-through;
#T=td-n
text-decoration:none;
#T=td-o
text-decoration:overline;
#T=td-u
text-decoration:underline;
#T=te
text-emphasis:^!;
#T=te-a
text-emphasis:after;
#T=te-ac
text-emphasis:accent;
#T=te-b
text-emphasis:before;
#T=te-c
text-emphasis:circle;
#T=te-ds
text-emphasis:disc;
#T=te-dt
text-emphasis:dot;
#T=te-n
text-emphasis:none;
#T=test
test(^!)
#T=textarea
<textarea name="^!"></textarea>
#T=textj
text(^!)
#T=tfloat
/*float*/ 
#T=tfoot
<tfoot>^!</tfoot>
#T=th
text-height:^!;
#T=th
<th>^!</th>
#T=th-a
text-height:auto;
#T=thead
<thead>^!</thead>
#T=th-f
text-height:font-size;
#T=th-m
text-height:max-size;
#T=th-t
text-height:text-size;
#T=thtml-3cols (wrap > head > content 3col > footer)
<div class="wrap">
  <div class="wrap-header">
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </div>
  <div class="wrap-content clearfix">
    <div class="wrap-left">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.	
    </div>
    <div class="wrap-center">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.	
    </div>
    <div class="wrap-right">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </div>
  </div>			
  <div class="wrap-footer">
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </div>
</div>
#T=thtml-bt1 (a > span)
<a href="#" class="bt1"><span>^!</span></a>
#T=thtml-bt1 (input > span >span)
<button class="input-bt" type="button"><span class="bt1" ><span>按钮</span></span></button>
#T=thtml-list (ul > li > a > span)
<ul class="list-fl clearfix">
  <li><a href="#"><span>豆瓣读书</span></a></li>
  <li><a href="#"><span>豆瓣读书</span></a></li>
  <li><a href="#"><span>豆瓣读书</span></a></li>
  <li><a href="#"><span>豆瓣读书</span></a></li>
  <li><a href="#"><span>豆瓣读书</span></a></li>
</ul>
#T=thtml-list (ul > li > a)
<ul class="list-fl clearfix">
  <li><a href="#">豆瓣读书</a></li>
  <li><a href="#">豆瓣读书</a></li>
  <li><a href="#">豆瓣读书</a></li>
  <li><a href="#">豆瓣读书</a></li>
  <li><a href="#">豆瓣读书</a></li>
  <li><a href="#">豆瓣读书</a></li>
  <li><a href="#">豆瓣读书</a></li>
</ul>

#T=thtml-list-nofl (ul > li > a > span)
<ul class="list-nofl clearfix">
  <li><a href="#"><span>美国夫妇在华救助数千孤残儿童 善款多来自美国</span></a></li>
  <li><a href="#"><span>美国夫妇在华救助数千孤残儿童 善款多来自美国</span></a></li>
  <li><a href="#"><span>美国夫妇在华救助数千孤残儿童 善款多来自美国</span></a></li>
  <li><a href="#"><span>美国夫妇在华救助数千孤残儿童 善款多来自美国</span></a></li>
</ul>
#T=thtml-list-nofl (ul > li > a)
<ul class="list-nofl clearfix">
  <li><a href="#">美国夫妇在华救助数千孤残儿童 善款多来自美国</a></li>
  <li><a href="#">美国夫妇在华救助数千孤残儿童 善款多来自美国</a></li>
  <li><a href="#">美国夫妇在华救助数千孤残儿童 善款多来自美国</a></li>
  <li><a href="#">美国夫妇在华救助数千孤残儿童 善款多来自美国</a></li>
  <li><a href="#">美国夫妇在华救助数千孤残儿童 善款多来自美国</a></li>
</ul>
#T=ti
text-indent:^!;
#T=ti--
text-indent:-9999px;
#T=time
<time>^!</time>
#T=tint
/*int*/ 
#T=title
<title>^!</title>
#T=tj
text-justify:^!;
#T=tj-a
text-justify:auto;
#T=tj-d
text-justify:distribute;
#T=tj-ic
text-justify:inter-cluster;
#T=tj-ii
text-justify:inter-ideograph;
#T=tj-iw
text-justify:inter-word;
#T=tj-k
text-justify:kashida;
#T=tj-t
text-justify:tibetan;
#T=to
text-outline:^!;
#T=to-
text-outline:0 0 #000;
#T=toArray
toArray(^!)
#T=tobject
/*object*/ 
#T=toDateString
toDateString(^!)
#T=toExponential
toExponential(^!)
#T=toFixed
toFixed(^!)
#T=toggle
toggle(^!)
#T=toggleClass
toggleClass(^!)
#T=toGMTString
toGMTString(^!)
#T=toLocaleDateString
toLocaleDateString(^!)
#T=toLocaleLowerCase
toLocaleLowerCase(^!)
#T=toLocaleString
toLocaleString(^!)
#T=toLocaleTimeString
toLocaleTimeString(^!)
#T=toLocaleUpperCase
toLocaleUpperCase(^!)
#T=toLowerCase
toLowerCase(^!)
#T=to-n
text-outline:none;
#T=toPrecision
toPrecision(^!)
#T=toStaticHTML
toStaticHTML(^!)
#T=toString
toString(^!)
#T=toTimeString
toTimeString(^!)
#T=toUpperCase
toUpperCase(^!)
#T=toUTCString
toUTCString(^!)
#T=tr
text-replace:^!;
#T=tr
<tr>^!</tr>
#T=tregexp
/*RegExp*/ 
#T=trigger
trigger(^!)
#T=tr-n
text-replace:none;
#T=try
try {
  ^!
}
catch () {
}
#T=tsh
text-shadow:^!;
#T=tsh-
text-shadow:0 0 0 #000;
#T=tsh-n
text-shadow:none;
#T=tstring
/*string*/ 
#T=tt
text-transform:^!;
#T=tt
/*^!*/ 
#T=tt-c
text-transform:capitalize;
#T=tt-l
text-transform:lowercase;
#T=tt-n
text-transform:none;
#T=tt-u
text-transform:uppercase;
#T=tvoid
/*void*/ 
#T=tw
text-wrap:^!;
#T=tw-n
text-wrap:normal;
#T=tw-no
text-wrap:none;
#T=tw-s
text-wrap:suppress;
#T=tw-u
text-wrap:unrestricted;
#T=typeof
typeof (^!)
#T=ubound
ubound(^!)
#T=ui-autoImg
/*???????????*/
function autoImg(ImgD, maxwidth, maxheight) {
  var image = new Image();
  image.src = ImgD.src;
  if (image.width > 0 && image.height > 0) {
    flag = true;
    if (image.width / image.height >= maxwidth / maxheight) {
      if (image.width > maxwidth) {
        ImgD.width = maxwidth;
        ImgD.height = (image.height * maxwidth) / image.width;
        } else {
          ImgD.width = image.width;
          ImgD.height = image.height;
        }
      }
    else {
       if (image.height > maxheight) {
         ImgD.height = maxheight;
         ImgD.width = (image.width * maxheight) / image.height;
       }else {
          ImgD.width = image.width;
          ImgD.height = image.height;
       }
    } 
  }
}
#T=ui-back-top
    <style type="text/css">
    .back-top {display: none;width: 18px;line-height: 1.2;padding: 5px 0;background-color: #000;color: #fff;font-size: 12px;text-align: center;position: fixed;_position:absolute;right: 112px;_right: 92px;bottom: 100px;_bottom: "auto";cursor: pointer;opacity: 0.6;filter: Alpha(opacity=60);}
    </style>
    <script type="text/javascript">
    //<![CDATA[

    //返回顶部
    (function() {
      var $backToTopTxt = "返回顶部", 
        $backToTopEle = $('<div class="back-top"></div>').appendTo($("body"))
        .text($backToTopTxt).attr("title", $backToTopTxt).click(function() {
            $("html, body").animate({ scrollTop: 0 }, 300);
        });

        $backToTopFun = function() {					
          var st = $(document).scrollTop(), winh = $(window).height();
          if(st > 200)
          {
            if($backToTopEle.data('pos') == 'top'){return false;} $backToTopEle.data('pos','top').stop().css('opacity','1').fadeIn();
          }else{
            if($backToTopEle.data('pos') == 'scroll'){return false;}
            $backToTopEle.data('pos','scroll').stop().fadeOut()
          }
        
          //IE6下的定位
          if (!window.XMLHttpRequest) {
            $backToTopEle.css("top", st + winh - 166);
          }
        };
      $(window).bind("scroll", $backToTopFun);
      $(function() { $backToTopFun(); });
    })();
#T=ui-blockShow
/*-- ????? --*/
+function ($) {
  'use strict';
   $.blockShow = function blockShow(objIn, objOut, callBack) {
    if (!objOut) {
      objIn.show();
      objIn[0].offsetWidth;
      objIn.addClass("in").one('bsTransitionEnd',function  () {
        $(this).removeClass("in");
      }).emulateTransitionEnd(220);
    }else {
      objOut.addClass("out").one('bsTransitionEnd', function  () {

      $(this).hide();
      $(this)[0].offsetWidth;
      $(this).removeClass("out");

      objIn.show();
      $(this)[0].offsetWidth;
      objIn.addClass("in").one('bsTransitionEnd',function  () {
        $(this).removeClass("in");
      }).emulateTransitionEnd(220);
      if (callBack) {
        callBack();
      }
      }).emulateTransitionEnd(220);
    }
  }

  $.blockHide = function blockHide(objOut, callBack) {
    objOut.addClass('out').one('bsTransitionEnd', function  () {
    $(this).hide().removeClass("out");

    if (callBack) {
      callBack();
    }
    }).emulateTransitionEnd(350);
  }
}(jQuery);
#T=ui-cooki
/*-- cooki???? --*/
function addCookie(objName,objValue,objHours){
  var str = objName + "=" + escape(objValue);
  if(objHours > 0){
    var date = new Date();
    var ms = objHours*3600*1000;
    date.setTime(date.getTime() + ms);
    str += "; expires=" + date.toGMTString();
  }
  document.cookie = str;
}

function getCookie(objName){
  var arrStr = document.cookie.split("; ");
  for(var i = 0;i < arrStr.length;i ++){
    var temp = arrStr[i].split("=");
    if(temp[0] == objName) return unescape(temp[1]);
  } 
}
#T=ui-countTime
//?????
jQuery(document).ready(function($) {
  var servertime = new Date("2015/01/22 23:08:28").getTime();
  var endtime = new Date("2015/01/21 17:42:00").getTime();
  var sbtime = (endtime - servertime) / 1e3;		
  var temp = "";
  var timese = "";

  if (sbtime <= 0) {
    temp = '<li class="cl1"><span style="color:#999;">00</span><span class="xq-zz none">??</span></li><li class="cl2" ><span style="color:#999;">00</span><span class="xq-zz none">?</span></li><li class="cl3"><span style="color:#999;">00</span><span class="xq-zz none">??</span></li><li class="cl4"><span style="color:#999;">00</span><span class="xq-zz none">??</span></li>';
    $("#timener ul").html(temp);
  } else {
    timese = setInterval(function() {
      timmer(sbtime);
    }, 1e3);
  }
  function timmer(getsc) {
    if (getsc > 0) {
      var second = Math.floor(getsc % 60);
      var minite = Math.floor(getsc / 60 % 60);
      var hour = Math.floor(getsc / 3600 % 24);
      var day = Math.floor(getsc / 3600 / 24);
      temp = '<li class="cl1"><span>' + day + '</span><span class="xq-zz none">??</span></li><li class="cl2"><span>' + hour + '</span><span class="xq-zz none">?</span></li><li class="cl3"><span>' + minite + '</span><span class="xq-zz none">??</span></li><li class="cl4"><span>' + second + '</span><span class="xq-zz none">??</span></li>';
      $("#timener ul").html(temp);
      sbtime--;
    } else {
      window.clearInterval(timese);
      location.reload();
    }
  }
})
#T=ui-fixtable
/*
fixhead($(".fixhead"));
<style type="text/css">
  .fixhead-box {width:800px; position:relative; border:1px solid #000;
  }
  .fixhead {width:800px;}
  .fixhead td,.fixhead th{border-bottom:1px solid #000;border-left:1px solid #000;}

  .fixhead-ct {height:170px; overflow:auto; overflow-x:hidden;}
  .fixhead-ct .trhd {visibility:hidden; display:none;}
  .fixhead-hd {height:22px; overflow:hidden; background:#fff; position:relative;}
</style>
*/
function fixhead(obj) {
  var clonetb = '';
  obj.find("th").each(function (n) {
      $(this).outerWidth($(this).outerWidth());
    obj.find("tr:eq(1) td:eq("+n+")").outerWidth($(this).outerWidth());
    if (n == obj.find("th").length-1) {
      clonetb = obj.clone();      
      obj.wrap('<div class="fixhead-box"></div>');
      obj.wrap('<div class="fixhead-ct"></div>');
            
      clonetb.insertBefore(obj.parent());
      clonetb.wrap('<div class="fixhead-hd"></div>');
      obj.find("tr").last().find("td").css("border-bottom","0");
    }
  })      
}
#T=ui-formCheck
/** 
* extend ???????????
* @author cuki13  
  .selectstyle {position:relative; border:1px solid #ccc; height:30px;display:inline-block;line-height:30px; width:100px; overflow:hidden;}
  .selectstyle select {position:absolute;left:0; top:0px; height:30px; margin:0; padding:0; width:100%; height:38px; }
  .selectstyle .val {display:block;}
  obj.each(function (n) {
      dataFormType($(this));
  })
*/

+function ($) {
  'use strict';
  var formSting = '[data-form="checkbox"]';
  
  var Radio = function  (number) {
    this.id = number;
  }
$(".ckiput").prop('checked',true);
  Radio.prototype.build = function  (el) {
    var setCss = {
      "opacity":"1",
      "position":"absolute"
    }
    var $this = $(el);
    $this.css(setCss);
    var idiv = $('<i></i>');
    idiv.insertBefore($this);
    $this.parent("label").css("position","relative");
    $this.on("change.resize",function  () { 
        
        if ($(this).prop('checked') == true) {
          $(this).parent("label").addClass("ck-select");    
        }else {
          $(this).parent("label").removeClass("ck-select");   
        }        
    });
  }

  function Plugin(option) {
    return this.each(function (n) {
      var $this   = $(this)
      var number = $this.attr('id') || n 
      var data    = $this.data('ck.select')
      var options = typeof option == 'object' && option
      if (!data) $this.data('ck.select', (data = new Radio(number)))
      if (option == 'build') data.build($(this))
      else if (option) data.setState(option)
    })
  }

  $(document).on('ready.ck.checkbox', function (e) {
    var $this = $(formSting);
    Plugin.call($this,'build');
  })
  
}(jQuery); 
#T=ui-formCheckbox
+(function ($) {
  'use strict';
  var formSting = '[data-form="checkbox"]';
  
  var checkbox = function  (number) {
    this.id = number;
  }

  checkbox.prototype.build = function  (el) {
    var setCss = {
      "opacity":"0",
      "position":"absolute",
      "left":'0'
    }
    var $this = $(el);
    $this.css(setCss);
    var idiv = $('<i></i>');
    idiv.insertBefore($this);
    $this.parent("label").css("position","relative");
    $this.on("change.resize",function  () {
     ($(this).prop('checked')) ? ($(this).parent("label").addClass("ck-checkbox-acitve") ) : ($(this).parent("label").removeClass("ck-checkbox-acitve"));
    });
  }

  function Plugin(option) {
    return this.each(function (n) {
      var $this   = $(this)
      var number = $this.attr('id') || n 
      var data    = $this.data('ck.checkbox')
      var options = typeof option == 'object' && option
      if (!data) $this.data('ck.checkbox', (data = new checkbox(number)))
      if (option == 'build') data.build($(this))
      else if (option) data.setState(option)
    })
  }

  $(document).on('ready.ck.checkbox', function (e) {
    var $this = $(formSting);
    Plugin.call($this,'build');
  })
  
  $.fn.formCheckbox = function  (options) {
    var $this = $(this);
    Plugin.call($this,'build');
  }

})(jQuery);
#T=ui-formRadio
/*-- ???radio [data-form="radio"] --*/
+function ($) {
  'use strict';
  var formSting = '[data-form="radio"]';
  
  var Radio = function  (number) {
    this.id = number;
  }

  Radio.prototype.build = function  (el) {
    var setCss = {
      "opacity":"0",
      "position":"absolute"
    }
    var $this = $(el);
    $this.css(setCss);
    var idiv = $('<i></i>');
    idiv.insertBefore($this);
    $this.parent("label").css("position","relative");
    $this.on("change.resize",function  () {      
        $(this).parent("label").addClass("ck-select").siblings("label").removeClass("ck-select");     
    });
  }

  function Plugin(option) {
    return this.each(function (n) {
      var $this   = $(this)
      var number = $this.attr('id') || n 
      var data    = $this.data('ck.select')
      var options = typeof option == 'object' && option
      if (!data) $this.data('ck.select', (data = new Radio(number)))
      if (option == 'build') data.build($(this))
      else if (option) data.setState(option)
    })
  }

  $(document).on('ready.ck.radio', function (e) {
    var $this = $(formSting);
    Plugin.call($this,'build');
  })
  
}(jQuery); 
#T=ui-formSelect
/** 
* extend ???????????
* @author cuki13  
  .selectstyle {position:relative; border:1px solid #ccc; height:30px;display:inline-block;line-height:30px; width:100px; overflow:hidden;}
  .selectstyle select {position:absolute;left:0; top:0px; height:30px; margin:0; padding:0; width:100%; height:38px; }
  .selectstyle .val {display:block;}
  obj.each(function (n) {
      dataFormType($(this));
  })
*/
(function() {
  var formSting = '[data-form="select"]';
  var Select = function  (number) {
    this.id = number;
  }

  Select.prototype.build = function  (el) {
    var $this = $(el);
    $this.css("opacity","0");
    $this.wrap("<span class='selectstyle'></span>");
    var gettxt = '<span class="val textb" >'+ $this.find("option:eq(0)").html()+'<i class="none"></i></span>';
    gettxt = $(gettxt);       
    gettxt.insertBefore($this);
    $this.parents(".selectstyle").addClass("select-"+ this.id);
    $this.on("change.resize",function  () {
      var vl = $(this).find("option:selected").html();
      $(this).prev('.val').html(vl);
      $(this).parents(".selectstyle").find('.val').html(vl);
    })
    $this.trigger('change.resize');
  }

  function Plugin(option) {
    return this.each(function (n) {
      var $this   = $(this)
      var number = $this.attr('id') || n 
      var data    = $this.data('ck.select')
      var options = typeof option == 'object' && option
      if (!data) $this.data('ck.select', (data = new Select(number)))
      if (option == 'build') data.build($(this))
      else if (option) data.setState(option)
    })
  }

  Select.init = function  () {
    var $this = $(formSting);
    Plugin.call($this,'build');
  }
  
  $(document).ready(function() {
    var $this = $(formSting);
    Plugin.call($this,'build');
  })

  $.fn.formSelect = function  (options) {
    var $this = $(this);
    Plugin.call($this,'build');
  }

})()
#T=ui-guagua
/** 
* extend ?ιο?????
*/
  function guagua() {
  //$("#canvas1").remove();
  //$(".content-box").append('<canvas id="canvas1" style=" background-repeat:no-repeat; background-position:center center;" />');
(function(bodyStyle) {
bodyStyle.mozUserSelect = 'none';
bodyStyle.webkitUserSelect = 'none';

var img = new Image();

var canvas = document.getElementById('canvas1');
var canvasbg = document.getElementById('canvasbg');

img.addEventListener('load', function(e) {
var ctx;
var ctxbg;
var w = 640,
h = 320;
var offsetX = canvas.offsetLeft,
offsetY = canvas.offsetTop;
var mousedown = false;

function getTransparentPercent(ctx, width, height) {
  var imgData = ctx.getImageData(0, 0, width, height),
    pixles = imgData.data,
    transPixs = [];
  for (var i = 0, j = pixles.length; i < j; i += 4) {
    var a = pixles[i + 3];
    if (a < 128) {
      transPixs.push(i);
    }
  }
  rate=(transPixs.length / (pixles.length / 4) * 100).toFixed(2);
   return rate
}


function layer(ctx) {
  var img1 = new Image();
  img1.onload = function() {    
    ctx.drawImage(img1, 0, 0, w, h);
    ctxbg.drawImage(img, (w-img.width)/2, (h-img.height)/2, img.width, img.height);    
    //canvas.style.backgroundImage='url('+img.src+')';
    ctx.globalCompositeOperation = 'destination-out';
  };
  img1.src = 'img/banner1.jpg';
  ctx.fillRect(0, 0, w, h);
}

function eventDown(e){
  e.preventDefault();
  mousedown=true;
}

function eventUp(e){
  e.preventDefault();
  mousedown=false;
}

function eventMove(e){
  e.preventDefault();
  if(mousedown) {
  if(e.changedTouches){
    e=e.changedTouches[e.changedTouches.length-1];
  }
  var x = (e.clientX + document.body.scrollLeft || e.pageX) - offsetX || 0,
  y = (e.clientY + document.body.scrollTop || e.pageY) - offsetY || 0;


  with(ctx) {
    
  beginPath();
  var radgrad = ctx.createRadialGradient(x, y, 0, x, y, 30);
  radgrad.addColorStop(0, 'rgba(0,0,0,1)');
  radgrad.addColorStop(1, 'rgba(255, 255, 255, 0)');
  ctx.fillStyle = radgrad;

  arc(x, y, 30, 0, Math.PI * 2);
  //ctx.clearRect(x, y, 440, 440);
  fill();
  }
  }
}

canvas.width=w;
canvasbg.width=w;
canvas.height=h;
canvasbg.height=h;

ctx=canvas.getContext('2d');
ctxbg=canvasbg.getContext('2d');
ctx.fillStyle='transparent';
ctx.fillRect(0, 0, w, h);
layer(ctx);

canvas.addEventListener('touchstart', eventDown);
canvas.addEventListener('touchend', eventUp);
canvas.addEventListener('touchmove', eventMove);
canvas.addEventListener('mousedown', eventDown);
canvas.addEventListener('mouseup', eventUp);
canvas.addEventListener('mousemove', eventMove);
});

//img.src = hideimg;

}) (document.body.style);
}


#T=ui-hoverdelay
// ????????з???
/*
$(this).hoverDelay({
  hoverEvent: function(){},
  outEvent:function  () {}
})
*/
+(function($){
  $.fn.hoverDelay = function(options){
    var defaults = {
      hoverDuring: 200,
      outDuring: 200,
      hoverEvent: function(){
        $.noop();
      },
      outEvent: function(){
        $.noop();    
      }
    };
    var sets = $.extend(defaults,options || {});
    var hoverTimer, outTimer, that = this;
    return $(this).each(function(){
      $(this).hover(function(){
        clearTimeout(outTimer);
        hoverTimer = setTimeout(function(){sets.hoverEvent.apply(that)}, sets.hoverDuring);
      },function(){
        clearTimeout(hoverTimer);
        outTimer = setTimeout(function(){sets.outEvent.apply(that)}, sets.outDuring);
      });
    });
  }      
})(jQuery);
#T=ui-imgload
var img = '<img />';
img = $("img");
img.attr("src","images/pic-fp.png");
if (img.complete) {
  
}else {
  img.load(function  () {

  })
}
#T=ui-inserChar
//?????????"," 112345 => 12,345
function  inserChar() {
  var gval = parseInt($("#result-number").data("number"));
  gval = parseInt((gval - Math.random()*100));

  gvalString = gval.toString();

  var long = gvalString.length;
  var mo = long%3 - 1;

  var string = '';
  for (var i = 0;  i<long ; i++) {
    string += gvalString.charAt(i);

    if (i == (mo)) {
      string += ',';
    }

    if (((i - mo)>0) && ((i - mo)%3) == 0 && (i<(long-1))) {
      string += ',';
    }                        
  }
}

#T=ui-Jseasing
/* jQuery EasIng v1.1.2 - http://gsgd.co.uk/sandbox/jquery.easIng.php
*
* Uses the built In easIng capabilities added In jQuery 1.1
* to offer multiple easIng options
*
* Copyright (c) 2007 George Smith
* Licensed under the MIT License:
*   http://www.opensource.org/licenses/mit-license.php
*/

// t: current time, b: begInnIng value, c: change In value, d: duration 动画特效

jQuery.extend(jQuery.easing, {
  easeInQuad : function(x, t, b, c, d) {
    return c * (t /= d) * t + b;
  },
  easeOutQuad : function(x, t, b, c, d) {
    return -c * (t /= d) * (t - 2) + b;
  },
  easeInOutQuad : function(x, t, b, c, d) {
    if((t /= d / 2) < 1)
      return c / 2 * t * t + b;
    return -c / 2 * ((--t) * (t - 2) - 1) + b;
  },
  easeInCubic : function(x, t, b, c, d) {
    return c * (t /= d) * t * t + b;
  },
  easeOutCubic : function(x, t, b, c, d) {
    return c * (( t = t / d - 1) * t * t + 1) + b;
  },
  easeInOutCubic : function(x, t, b, c, d) {
    if((t /= d / 2) < 1)
      return c / 2 * t * t * t + b;
    return c / 2 * ((t -= 2) * t * t + 2) + b;
  },
  easeInQuart : function(x, t, b, c, d) {
    return c * (t /= d) * t * t * t + b;
  },
  easeOutQuart : function(x, t, b, c, d) {
    return -c * (( t = t / d - 1) * t * t * t - 1) + b;
  },
  easeInOutQuart : function(x, t, b, c, d) {
    if((t /= d / 2) < 1)
      return c / 2 * t * t * t * t + b;
    return -c / 2 * ((t -= 2) * t * t * t - 2) + b;
  },
  easeInQuint : function(x, t, b, c, d) {
    return c * (t /= d) * t * t * t * t + b;
  },
  easeOutQuint : function(x, t, b, c, d) {
    return c * (( t = t / d - 1) * t * t * t * t + 1) + b;
  },
  easeInOutQuint : function(x, t, b, c, d) {
    if((t /= d / 2) < 1)
      return c / 2 * t * t * t * t * t + b;
    return c / 2 * ((t -= 2) * t * t * t * t + 2) + b;
  },
  easeInSine : function(x, t, b, c, d) {
    return -c * Math.cos(t / d * (Math.PI / 2)) + c + b;
  },
  easeOutSine : function(x, t, b, c, d) {
    return c * Math.sin(t / d * (Math.PI / 2)) + b;
  },
  easeInOutSine : function(x, t, b, c, d) {
    return -c / 2 * (Math.cos(Math.PI * t / d) - 1) + b;
  },
  easeInExpo : function(x, t, b, c, d) {
    return (t == 0) ? b : c * Math.pow(2, 10 * (t / d - 1)) + b;
  },
  easeOutExpo : function(x, t, b, c, d) {
    return (t == d) ? b + c : c * (-Math.pow(2, -10 * t / d) + 1) + b;
  },
  easeInOutExpo : function(x, t, b, c, d) {
    if(t == 0)
      return b;
    if(t == d)
      return b + c;
    if((t /= d / 2) < 1)
      return c / 2 * Math.pow(2, 10 * (t - 1)) + b;
    return c / 2 * (-Math.pow(2, -10 * --t) + 2) + b;
  },
  easeInCirc : function(x, t, b, c, d) {
    return -c * (Math.sqrt(1 - (t /= d) * t) - 1) + b;
  },
  easeOutCirc : function(x, t, b, c, d) {
    return c * Math.sqrt(1 - ( t = t / d - 1) * t) + b;
  },
  easeInOutCirc : function(x, t, b, c, d) {
    if((t /= d / 2) < 1)
      return -c / 2 * (Math.sqrt(1 - t * t) - 1) + b;
    return c / 2 * (Math.sqrt(1 - (t -= 2) * t) + 1) + b;
  },
  easeInElastic : function(x, t, b, c, d) {
    var s = 1.70158;
    var p = 0;
    var a = c;
    if(t == 0)
      return b;
    if((t /= d) == 1)
      return b + c;
    if(!p)
      p = d * .3;
    if(a < Math.abs(c)) {
      a = c;
      var s = p / 4;
    } else
      var s = p / (2 * Math.PI) * Math.asin(c / a);
    return -(a * Math.pow(2, 10 * (t -= 1)) * Math.sin((t * d - s) * (2 * Math.PI) / p)) + b;
  },
  easeOutElastic : function(x, t, b, c, d) {
    var s = 1.70158;
    var p = 0;
    var a = c;
    if(t == 0)
      return b;
    if((t /= d) == 1)
      return b + c;
    if(!p)
      p = d * .3;
    if(a < Math.abs(c)) {
      a = c;
      var s = p / 4;
    } else
      var s = p / (2 * Math.PI) * Math.asin(c / a);
    return a * Math.pow(2, -10 * t) * Math.sin((t * d - s) * (2 * Math.PI) / p) + c + b;
  },
  easeInOutElastic : function(x, t, b, c, d) {
    var s = 1.70158;
    var p = 0;
    var a = c;
    if(t == 0)
      return b;
    if((t /= d / 2) == 2)
      return b + c;
    if(!p)
      p = d * (.3 * 1.5);
    if(a < Math.abs(c)) {
      a = c;
      var s = p / 4;
    } else
      var s = p / (2 * Math.PI) * Math.asin(c / a);
    if(t < 1)
      return -.5 * (a * Math.pow(2, 10 * (t -= 1)) * Math.sin((t * d - s) * (2 * Math.PI) / p)) + b;
    return a * Math.pow(2, -10 * (t -= 1)) * Math.sin((t * d - s) * (2 * Math.PI) / p) * .5 + c + b;
  },
  easeInBack : function(x, t, b, c, d, s) {
    if(s == undefined)
      s = 1.70158;
    return c * (t /= d) * t * ((s + 1) * t - s) + b;
  },
  easeOutBack : function(x, t, b, c, d, s) {
    if(s == undefined)
      s = 1.70158;
    return c * (( t = t / d - 1) * t * ((s + 1) * t + s) + 1) + b;
  },
  easeInOutBack : function(x, t, b, c, d, s) {
    if(s == undefined)
      s = 1.70158;
    if((t /= d / 2) < 1)
      return c / 2 * (t * t * (((s *= (1.525)) + 1) * t - s)) + b;
    return c / 2 * ((t -= 2) * t * (((s *= (1.525)) + 1) * t + s) + 2) + b;
  },
  easeInBounce : function(x, t, b, c, d) {
    return c - jQuery.easing.easeOutBounce(x, d - t, 0, c, d) + b;
  },
  easeOutBounce : function(x, t, b, c, d) {
    if((t /= d) < (1 / 2.75)) {
      return c * (7.5625 * t * t) + b;
    } else if(t < (2 / 2.75)) {
      return c * (7.5625 * (t -= (1.5 / 2.75)) * t + .75) + b;
    } else if(t < (2.5 / 2.75)) {
      return c * (7.5625 * (t -= (2.25 / 2.75)) * t + .9375) + b;
    } else {
      return c * (7.5625 * (t -= (2.625 / 2.75)) * t + .984375) + b;
    }
  },
  easeInOutBounce : function(x, t, b, c, d) {
    if(t < d / 2)
      return jQuery.easing.easeInBounce(x, t * 2, 0, c, d) * .5 + b;
      return jQuery.easing.easeOutBounce(x, t * 2 - d, 0, c, d) * .5 + c * .5 + b;
  }
});
#T=ui-mobileTouch
+(function ($) {
  'use strict';
  var touch = {},
      touchTimeout, tapTimeout, swipeTimeout, longTapTimeout,
      longTapDelay = 750,
      gesture

  function swipeDirection(x1, x2, y1, y2) {
    return Math.abs(x1 - x2) >=
    Math.abs(y1 - y2) ? (x1 - x2 > 0 ? 'Left' : 'Right') : (y1 - y2 > 0 ? 'Up' : 'Down')
  }

  function longTap() {
    longTapTimeout = null
    if (touch.last) {
      touch.el.trigger('longTap')
      touch = {}
    }
  }

  function cancelLongTap() {
    if (longTapTimeout) clearTimeout(longTapTimeout)
    longTapTimeout = null
  }

  function cancelAll() {
    if (touchTimeout) clearTimeout(touchTimeout)
    if (tapTimeout) clearTimeout(tapTimeout)
    if (swipeTimeout) clearTimeout(swipeTimeout)
    if (longTapTimeout) clearTimeout(longTapTimeout)
    touchTimeout = tapTimeout = swipeTimeout = longTapTimeout = null
    touch = {}
  }

  function isPrimaryTouch(event) {
    return (event.pointerType == 'touch' ||
    event.pointerType == event.MSPOINTER_TYPE_TOUCH)
    && event.isPrimary
  }

  function isPointerEventType(e, type) {
    return (e.type == 'pointer' + type ||
    e.type.toLowerCase() == 'mspointer' + type)
  }

  $(document).ready(function () {
    var now, delta, deltaX = 0, deltaY = 0, firstTouch, _isPointerType

    if ('MSGesture' in window) {
      gesture = new MSGesture()
      gesture.target = document.body
    }

    $(document)
        .bind('MSGestureEnd', function (e) {
          var swipeDirectionFromVelocity =
              e.velocityX > 1 ? 'Right' : e.velocityX < -1 ? 'Left' : e.velocityY > 1 ? 'Down' : e.velocityY < -1 ? 'Up' : null;
          if (swipeDirectionFromVelocity) {
            touch.el.trigger('swipe')
            touch.el.trigger('swipe' + swipeDirectionFromVelocity)
          }
        })
        .on('touchstart MSPointerDown pointerdown', function (e) {
          if ((_isPointerType = isPointerEventType(e, 'down')) && !isPrimaryTouch(e)) return

          firstTouch = _isPointerType ? e : window.event.touches[0]
          if (e.touches && e.touches.length === 1 && touch.x2) {
            // Clear out touch movement data if we have it sticking around
            // This can occur if touchcancel doesn't fire due to preventDefault, etc.
            touch.x2 = undefined
            touch.y2 = undefined
          }
          now = Date.now()
          delta = now - (touch.last || now)
          touch.el = $('tagName' in firstTouch.target ?
              firstTouch.target : firstTouch.target.parentNode)
          touchTimeout && clearTimeout(touchTimeout)
          touch.x1 = firstTouch.pageX
          touch.y1 = firstTouch.pageY
          if (delta > 0 && delta <= 250) touch.isDoubleTap = true
          touch.last = now
          longTapTimeout = setTimeout(longTap, longTapDelay)
          // adds the current touch contact for IE gesture recognition
          if (gesture && _isPointerType) gesture.addPointer(e.pointerId);
        })
        .on('touchmove MSPointerMove pointermove', function (e) {
          if ((_isPointerType = isPointerEventType(e, 'move')) && !isPrimaryTouch(e)) return
          firstTouch = _isPointerType ? e : window.event.touches[0]
          cancelLongTap()
          touch.x2 = firstTouch.pageX
          touch.y2 = firstTouch.pageY

          deltaX += Math.abs(touch.x1 - touch.x2)
          deltaY += Math.abs(touch.y1 - touch.y2)
          e.preventDefault();
        })
        .on('touchend MSPointerUp pointerup', function (e) {
          if ((_isPointerType = isPointerEventType(e, 'up')) && !isPrimaryTouch(e)) return
          cancelLongTap()

          // swipe
          if ((touch.x2 && Math.abs(touch.x1 - touch.x2) > 30) ||
              (touch.y2 && Math.abs(touch.y1 - touch.y2) > 30))

            swipeTimeout = setTimeout(function () {
              touch.el.trigger('swipe')
              touch.el.trigger('swipe' + (swipeDirection(touch.x1, touch.x2, touch.y1, touch.y2)))
              touch = {}
            }, 0)

          // normal tap
          else if ('last' in touch)
          // don't fire tap when delta position changed by more than 30 pixels,
          // for instance when moving to a point and back to origin
            if (deltaX < 30 && deltaY < 30) {
              // delay by one tick so we can cancel the 'tap' event if 'scroll' fires
              // ('tap' fires before 'scroll')
              tapTimeout = setTimeout(function () {

                // trigger universal 'tap' with the option to cancelTouch()
                // (cancelTouch cancels processing of single vs double taps for faster 'tap' response)
                var event = $.Event('tap')
                event.cancelTouch = cancelAll
                touch.el.trigger(event)

                // trigger double tap immediately
                if (touch.isDoubleTap) {
                  if (touch.el) touch.el.trigger('doubleTap')
                  touch = {}
                }

                // trigger single tap after 250ms of inactivity
                else {
                  touchTimeout = setTimeout(function () {
                    touchTimeout = null
                    if (touch.el) touch.el.trigger('singleTap')
                    touch = {}
                  }, 250)
                }
              }, 0)
            } else {
              touch = {}
            }
          deltaX = deltaY = 0

        })
      // when the browser window loses focus,
      // for example when a modal dialog is shown,
      // cancel all ongoing events
        .on('touchcancel MSPointerCancel pointercancel', cancelAll)

    // scrolling the window indicates intention of the user
    // to scroll, not tap or swipe, so cancel all ongoing events
    $(window).on('scroll', cancelAll)
  })

  ;
  ['swipe', 'swipeLeft', 'swipeRight', 'swipeUp', 'swipeDown',
    'doubleTap', 'tap', 'singleTap', 'longTap'].forEach(function (eventName) {
        $.fn[eventName] = function (callback) {
          return this.on(eventName, callback)
        }
      })

})(jQuery);

#T=ui-pop
/** 
* extend ??????
* @author cuki13
  $(obj).popbk();
  .popbk-wrap {position: fixed; top: 0; left: 0; bottom: 0; right: 0; overflow: auto; z-index:100;}
  .popbk {position: absolute; top:0; left:50%;}
  .popbk .close {position:absolute;right:0;top:0;}
  .fade.in { opacity: 1; }
  .fade{opacity: 0;-webkit-transition: opacity .15s linear;-o-transition: opacity .15s linear;transition: opacity .15s linear;}
  $("#popbk2").data('ck.pokbk').open();
  $("#popbk2").data('ck.pokbk').close();
*/

+(function($){
  var dataString = '[data-box="popbk"]';
  
  var Popbk = function  (el, number ,options) {
    this.el = $(el)
    this.id = number
    this.options = $.extend({}, this.defualts, options); 
  }
  
  Popbk.defualts = {};

  Popbk.prototype.build = function  (el) {
    
    var $this = $(el);
    $this.wrap('<div class="popbk-wrap-'+ this.id +' popbk-wrap fade" ></div>');
    $this.wrap('<div class="popbk-'+ this.id +' popbk" ></div>');

    var sClose = "<a class='close'><span class='none'>close</span></a>";
    sClose = $(sClose);
    sClose.insertAfter($this);
    var ml = $this.width()/2;     
    $this.parent(".popbk").css("margin-left",-ml);
    
    var wh = $this.height();
    if ($(window).height < wh) {
      $this.parent(".popbk").css("top","30px");
    }else {
      $this.parent(".popbk").css({
        "margin-top":-wh/2,
        "top":'50%'
      });
    }
    $this.parent(".popbk").find(".close").on('click',function  () {
      $this.data('ck.pokbk').close();
    })    
    $this.parents(".popbk-wrap").hide();
  }

  Popbk.prototype.open = function  () {
    this.close;
    var $this = this.el;
    if ($this.length) {
      $this.parents(".popbk-wrap").show();
      $this.parents(".popbk-wrap")[0].offsetWidth;
      $this.parents(".popbk-wrap").addClass("in");
    }
  }

  Popbk.prototype.close = function  () {
    var $this = this.el;
    var $parent = $this.parents(".popbk-wrap");
    if ($.support.transition && $parent.hasClass('fade')) {
      $parent.removeClass("in");
      $parent.one('bsTransitionEnd', function  () {
          $parent.hide();
        }).emulateTransitionEnd(150);
    }else {
      $parent.hide();
    }
  }

  function Plugin(option) {
    return this.each(function (n) {
      var $this   = $(this)
      var data    = $this.data('ck.pokbk')
      var number = $this.attr('id') || n 
      var options = typeof option == 'object' && option
      if (!data) $this.data('ck.pokbk', (data = new Popbk(this,number)))
      if (option == 'build') data.build($(this))
      else if (option) data.setState(option)
    })
  }

  $(document).on('ready.popbk', function  () {
    var $this = $(dataString);
    Plugin.call($this,'build');
  })
})(jQuery);
#T=ui-randomColor
/* ??????? */
+function ($) {
  'use strict';
  var srand = '[data-dismiss="srand"]';
  var Rand   = function () {}
  Rand.prototype.rcolor = function  () {
    //16????????????0-F
    var arrHex = ["0","1","2","3","4","5","6","7","8","9","A","B","C","D","E","F"];
    var strHex = "#";
    var index;
    for(var i = 0; i < 6; i++) {
      //???0-15???????????
      index = Math.round(Math.random() * 15);
      strHex += arrHex[index];
    }

    var $this = $(this);
    $this.html(strHex);
  }
  $(document).on('click', srand, Rand.prototype.rcolor);
}(jQuery);
#T=ui-reload
/** 
* extend ????????
* 
* @package jquery
* @author cuki13
*/
+(function($){
  'use strict';
  var ajax = null;
  var urlLink = function  (el) {
    this.$el = $(el) || null;
    this.url = $(el).attr("href") || null;
  }
  urlLink.prototype.jump = function  () {
    var $this = this;
    $.ajax({
      type: "POST",
      url: $this.url,
      //dataType: 'json',
      success: function(data){
       $.blockHide($("#loading-wrap"));
        var cotenData = null;
        var data = $(data);
        var gTitle = null;
        $(data).each(function (n) {
          var findContainer = $(data)[n];
          var container = $(findContainer);
          if (container.is("title")) {
            gTitle = $($(data)[n]).html();
          }
          if (container.hasClass("container")) {
            cotenData = findContainer.outerHTML;
           
            if ($.support.transition) {
              $(".container").addClass("out").one('bsTransitionEnd',function  () {
                $(".container").removeClass("out");
                $(".container").replaceWith(container);
                
                container.addClass("in");
                setTimeout(
                  function(){
                    container.removeClass("in");
                  }, 320);
              }).emulateTransitionEnd(320);
            }else {
              $(".container").replaceWith(container);
            }
            return false;
          }
        })
        document.title = gTitle;
        var state = {
          url: $this.url,
          title: document.title,
          getHtml: cotenData
        };

        history.pushState(state,gTitle,$this.url);
        ajax = true;
      },
      error:function  () {
        alert('????????????????????????');
        $.blockHide($("#loading-wrap"));
      },
      beforeSend:function  () {
        $.blockShow($("#loading-wrap"));
      }
    });
  }

  $(document).ready(function() {
    urlLink.currentState = {
      url : document.location.href,
      title :  document.title,
      getHtml : $(".container")[0].outerHTML
    }

    //history.pushState(urlLink.currentState,document.title,location.href);
    $("body").on('click','[data-url="true"]',function  (e) {
      e.preventDefault();
      $(this).data("url",new urlLink(this));
      $(this).data("url").jump();
    })
  })



  window.addEventListener("popstate",function(event){
    if(event && event.state){
      var gcontent = $(event.state.getHtml);
      $(".container").replaceWith(gcontent);
      $(".container").removeClass("out");
      document.title = event.state.title;
    }else{
      if (ajax == null) {
        return false;
      }
      document.title = urlLink.currentState.title;
      $(".container").replaceWith(urlLink.currentState.getHtml);
      $(".container").removeClass("out");
    }
  });

 $.pUrl = function (url) {
   var blink = new urlLink();
   blink.url = url;
   blink.jump();
 }

})(jQuery);
#T=ui-scollUp
/** 
* extend ?????????????
* @author cuki13
  $(obj).scollUp({
    speed:3000,
    scolldiv:'.scolldiv'
  })
*/
+(function($){
  $.fn.scollUp = function (options) {
    var obj=$(this);
    var defualts = {
      scolldiv:'.scolldiv'
    };
    var opts = $.extend({}, defualts, options);  

    var MyMar = 0;
    var scolldiv = obj.find(opts.scolldiv);
    var objclone = obj.find(opts.scolldiv).clone();
    objclone.appendTo(obj);
    function Marquee() {
       if(objclone.offset().top - obj.offset().top <=0){
          obj.scrollTop(0);
         }else{
           if ((obj.scrollTop())%(objclone.height()/2) == 0) {
            clearInterval(MyMar);
            setTimeout(
              function(){
                clearInterval(MyMar);
                MyMar=setInterval(Marquee,speed);
              }, 3000)

           }
            var k = obj.scrollTop();
            obj.scrollTop(k+1);
         }
    }

     MyMar=setInterval(Marquee,speed);

     obj.hover(function  () {
      clearInterval(MyMar);
     },function  () {
      clearInterval(MyMar);
      MyMar=setInterval(Marquee,speed);
     })
    
  };  
})(jQuery);
#T=ui-scrolleffect
/* ========================================================================
????????Ч??
 */
+function ($) {
  "use strict";
  var scrollEffe = function  (groudEl) {
    this.groudEl = groudEl;
    this.$el = [];
    this.$parentEl = [];
    this.startPro = [];
    for (var i = 0;  i<groudEl.length ; i++) {
      this.$el[i] = groudEl[i][0];
      this.$parentEl[i] = groudEl[i][1];
      this.startPro[i] = groudEl[i][5];
      this.initPosFun(this.$el[i],groudEl[i][2],groudEl[i][3],groudEl[i][4]);
    }

    this.initScroll();

  }

  scrollEffe.prototype.initPosFun =function  ($dom,tempX,tempY,type) {
    if (!type) {
      type = "moveblock";
    }
    tempX = tempX || 0;
    tempY = tempY || 0;
    $dom.data("endX",parseFloat($dom.css("left")));
    $dom.data("startX",parseFloat($dom.css("left"))+tempX);
    $dom.data("tempX",tempX);

    $dom.data("endY",parseFloat($dom.css("top")));
    $dom.data("startY",parseFloat($dom.css("top"))+tempY);
    $dom.data("tempY",tempY);

    $dom.css({"left":$dom.data("startX"),"top":$dom.data("startY")});
  }

  scrollEffe.prototype.posMoveFun = function($dom,$domParent,plong)
  {
      var permb = 0;
      if (plong) {
        permb = plong;
      }else {
        permb = 0;
      }
      //???????????????????
      var tempY = $(document).scrollTop()-$domParent.position().top + permb;
      var per = Math.max(-tempY/800,0);
      var targetX = $dom.data("endX")+$dom.data("tempX")*per;
      var targetY = $dom.data("endY")+$dom.data("tempY")*per;
      $dom.css({"left":targetX,"top":targetY});
  }


  scrollEffe.prototype.opacity = function($dom,$domParent,ease)
  {
    //???????????????????
    var tempY = $(document).scrollTop()-$domParent.position().top;
    var opacity = Math.min(tempY*0.008,1);
    $dom.css("opacity",opacity);
  };

  scrollEffe.prototype.scale = function($dom,$domParent,ease)
  {
    //???????????????????
    var tempY = $(document).scrollTop()-$domParent.position().top + $(window).height()/2;

    var scale = Math.min(tempY*0.003,1);
    if (scale < 0) {
      scale = 0
    }
    $dom.css("transform","scale(" + scale + ")");
  };


  scrollEffe.prototype.initScroll = function  () {
    var $this = this;
    $(window).bind("scroll",function(){
      for (var i = 0;  i<$this.groudEl.length ; i++) {
        switch ($this.groudEl[i][4]) {
        case 'moveblock':
          $this.posMoveFun($this.$el[i],$this.$parentEl[i],$this.startPro[i]);
        break
        case 'opacity':
         $this.opacity($this.$el[i],$this.$parentEl[i]);
        case 'scale':
         $this.scale($this.$el[i],$this.$parentEl[i]);
        break
        default:
        }
           
      }
    })
  }

  $(document).ready(function() {
      //???????
      if ($('body.home').length > 0) {
        var blockSilder = [
          [$(".server-block1"),$("#server-container"),-700,-600-300,'moveblock'],
          [$(".server-block2"),$("#server-container"),-1500,-600+300,'moveblock'],
          [$(".server-block3"),$("#server-container"),0,500,'moveblock'],
          [$(".server-block4"),$("#server-container"),300,-600-300,'moveblock'],
          [$(".server-box-top"),$("#server-container"),0, -1200,'moveblock'],
          [$(".advantage-ct-pk"),$("#advantage-container"),0.5, 1,'scale'],
          [$(".advantage-cir-active"),$("#advantage-container"),-500, 0,'moveblock'],
          [$(".advantage-cir-media"),$("#advantage-container"),0, -500,'moveblock'],
          [$(".advantage-cir-design"),$("#advantage-container"),-300, 500,'moveblock'],
          [$(".advantage-cir-power"),$("#advantage-container"),-300, -500,'moveblock'],
          [$(".advantage-cir-brand"),$("#advantage-container"),300, -500,'moveblock'],
          [$(".advantage-cir-res"),$("#advantage-container"),-300, 500,'moveblock'],
          [$(".team-box-txt"),$("#team-container"),-600, 0,'moveblock'],
          [$(".team-ld"),$("#team-container"),600, 0,'moveblock'],
          [$(".news-list"),$("#news-container"),0, 700,'moveblock'],
          [$(".contact-adress"),$("#contact-container"),-500, 0,'moveblock',500],
          [$(".share-box"),$("#contact-container"),500, 0,'moveblock',500]
        ]
        var $serverBlock1 = new scrollEffe(blockSilder);
      }
  })
}(jQuery);
#T=ui-scrollPic
/** 
* extend ?????
* 
* @package jquery
* @author cuki13
   $("#scrollpic").scollpic({
    itemTag : "li",
    itemWidth : 157,
    itemHeight : 250,
    bigImg : 'off',
    scollBack : function  (img , obj) {
      //??????????????
    }
   });

  //css
  .scrolllist li{
    float:left;
    width:157px;
    list-style-type:none;
  }
  .scrolllist img {
    width:100%;
    height:100%;
  }
  .scroll-warp {
    width:300px;
  }
*/

+(function($){
/**
 * Checks for CSS support.
 * @private
 * @param {Array} array - The CSS properties to check for.
 * @returns {Array} - Contains the supported CSS property name and its index or `false`.
 */
function isStyleSupported(array) {
  var p, s, fake = document.createElement('div'), list = array;
  for (p in list) {
    s = list[p];
    if (typeof fake.style[s] !== 'undefined') {
      fake = null;
      return [ s, p ];
    }
  }
  return [ false ];
}

/**
 * Checks for CSS transition support.
 * @private
 * @todo Realy bad design
 * @returns {Number}
 */
function isTransition() {
  return isStyleSupported([ 'transition', 'WebkitTransition', 'MozTransition', 'OTransition' ])[0];
}

/**
 * Checks for CSS transform support.
 * @private
 * @returns {String} The supported property name or false.
 */
function isTransform() {
  return isStyleSupported([ 'transform', 'WebkitTransform', 'MozTransform', 'OTransform', 'msTransform' ])[0];
}

$.fn.scollpic= function (options) {
  //??????
  $(this).each(function  () {
    var $this = $(this);
    var defualts = {
      itemTag : "li",
      itemWidth : 157,
      itemHeight : 150,
      itemCount: 4,
      bigImg : 'off',
      loop : true,
      wrapClass :'scrollpic-wrap',
      parenWidth : 'auto',
      playSpeed : 3000,
      autoPlay : false
    };

    var opts = $.extend({},defualts,options);

   

    var ifLoad = false; //??????
    var currentItemIndex = 0 ; //???item????
    if (opts.parenWidth == 'auto') {
      opts.parenWidth = parseInt(opts.itemCount * opts.itemWidth);
    }

    var $wrapObj=$('<div class="' + opts.wrapClass + '"></div>');

    $wrapObj.css({'position':'relative','height':opts.itemHeight});

    //??????
    if (opts.itemWidth == 'auto') {
      opts.itemWidth = $(this).find(opts.sdiv).width();
    }
    
    $this.wrap($wrapObj);

    var $arrowPrev=$('<a href="javascript:void(0);" class="scroll-item-list-prev endprev st"><span class="v-h">prev</span></a>');
    var $arrowNext=$('<a href="javascript:void(0);" class="scroll-item-list-next st"><span class="v-h">next</span></a>');

    $this.parent().append($arrowPrev).append($arrowNext);

    $this.wrap('<div class="scroll-warp" style="overflow:hidden; position:relative; height:' + opts.itemHeight + 'px; width:' + opts.parenWidth + 'px;"></div>');

    $arrowPrev.click(function  () {
      scoll('left',$this);
    });

    $arrowNext.click(function  () {
      scoll('right',$this);
    });

    //???
    var navItemCount = $this.find(opts.itemTag).length / opts.itemCount;
    function  nav() {
      var html = '<div class="banner-nav">';
      for (var i = 0; i < navItemCount; i++) {
        html += '<a class="' + (i == 0 ? 'current' : '' ) + ' sort-' + i + ' " data="'+ i +'" href="javascript:void(0);"><span>'+(i+1)+'</span></a>';
      }
      html += '</div>';
      return $(html);
    }
    var $nav = nav();

    $nav.appendTo($this.parent().parent());
    $nav.find("a").click(function  () {
      if ($(this).hasClass("current")) {
        return false;
      }else {
        $(this).addClass("current").siblings().removeClass("current");
        var ind = $(this).index();
        var scrollWidth = $(this).index() * opts.itemCount * opts.itemWidth;
        scrollWidth = scrollWidth + (opts.itemCount * opts.itemWidth);
        console.log(scrollWidth,ind);
        scoll('nav', $this, scrollWidth);
      }
    })

    //??????
    if (opts.loop == true) {
      var totleCount = $this.find(opts.itemTag).length;
      var $prevClone = $this.find(opts.itemTag + ':gt(' + (totleCount - opts.itemCount - 1) + ')').clone().addClass("clone");
      var $nextClone = $this.find(opts.itemTag + ':lt(' + opts.itemCount + ')').clone().addClass("clone");
      $nextClone.appendTo($this);
      $prevClone.prependTo($this);
    }

    //?????
    var itemTotal=0; 

    $this.find(opts.itemTag).last().css("padding-right","0");
    $this.find(opts.itemTag).each(function  () {     
      itemTotal+=$(this).outerWidth();
    });
    $this.css({'position':'relative','width':itemTotal});    

    //moblie tounch??????
    var currntp = 0;
    var pageX = 0;
    var ifchlick = false;
      
    $this.parents("."+opts.wrapClass).bind("touchstart",function  (e) {
       currntp = window.event.touches[0].pageX;
       ifchlick = true;
       e.preventDefault();
     });

    $this.parents("."+opts.wrapClass).bind('touchend', function(e) {
      if (pageX == 0) {
        return false;
      }
      e.preventDefault();
      ifchlick = false;
      var widthStep = 10;
      
      if ((Math.abs(currntp - pageX) >= widthStep)) {
        if (currntp - pageX >= widthStep) {
          $arrowNext.trigger('click');          
        } else {          
          $arrowPrev.trigger('click');
        }
      }
      currntp = 0;
      pageX = 0;
    });

    $this.parents("."+opts.wrapClass).bind('touchmove', function(e) {
      e.preventDefault();
      if (ifchlick) {
        ifchlick = false;
        pageX = window.event.targetTouches[0].pageX;
      }else {
        return false;
      }
    });
    
    //?????????
    $this.find(opts.itemTag).find("a").click(function  (e) {
      var $item = $(this);
      if (opts.bigImg && (opts.bigImg == 'off')) {
        return false;
      }else{

      if(ifLoad == true || $item.parent().hasClass('current')){ return false;}

      currentItemIndex = $this.find(opts.itemTag + '.current').index();
      
      if ((currentItemIndex!= -1) && (currentItemIndex!= 0) && (currentItemIndex!= ($this.find(opts.itemTag).length-1))) {
        var itemIndex = $item.parent().index();
        if (currentItemIndex > itemIndex) {
          $arrowPrev.trigger('click');
        }else {
          $arrowNext.trigger('click');
        }
      }

      $item.parent().siblings('li').removeClass('current');
      $item.parent().addClass('current');

      if (opts.bigImg) {
        showImg(opts.bigImg,$item.attr("href"),$item);
      }      
      e.preventDefault();
      }
    })

    //???
    var onHover = false;
    $this.hover(function  () {
      onHover = true;
    },function  () {
      onHover = false;
    })

    function loopMain() {
      if (opts.autoPlay == true) {
        if (onHover == false) {
          $arrowNext.trigger('click');
        }
      }
    }
    
    var timecount = setInterval(function  () {
      loopMain();
    }, opts.playSpeed);
    
    var ajaxLoad = $('<div id="loading" class="loading yh"><i></i><span>?????С?????</span></div>');
    var showImg = function (obj,data,objlink) {
      var img = $('<img src="' + data + '" />');
      ajaxLoad.insertBefore(obj);
      ifload = true;
      
      if (img[0].complete) {
        if (opts.ppscollcallback) {
          opts.ppscollcallback(obj,objlink);
        }
        obj.hide().attr('src', data).fadeIn();
        ajax_load.detach();
        ifload = false;

      }else {
        img.load(function  () {
        if (opts.scollBack) {
          opts.scollBack(obj,objlink);
        }
        obj.hide().attr('src', data).fadeIn();
        ajaxLoad.detach();
        ifload = false;
        }).error(function(){
          ajaxLoad.detach();
          alert('????,???????');
          ifload = false;
        });
      }
    }

    var ifScroll = false;

    var scrollEg = isTransform() ? isTransform()  : 'left';
    
    var leftVal = 0;

    //????????
    function  loopRest() {
      if (opts.loop == true) {
        $this.css("transition","0"); 
        scrollObj($this, -(opts.itemCount*opts.itemWidth),'nav', function  () {
          $this.css("transition","0.5s");
        });
      }
    }

    function  loopRestEnd() {
      if (opts.loop == true) {
        $this.css("transition","0"); 
        scrollObj($this, -(itemTotal - (opts.itemCount*opts.itemWidth)*2),'nav', function  () {
          $this.css("transition","0.5s");
        });
      }
    }


    loopRest();

    //??????
    function  scrollObj(obj, value, navlong, callback) {
      if (navlong) {
         leftVal = 0;
      }
      cssSet = {};
      if (scrollEg != 'left') {
        var noPos = obj.css("");

        switch (scrollEg) {
        case 'transform':
            cssSet = {'transform' : 'translateX(' + (leftVal + value) + 'px)'};
        break
        case 'WebkitTransform':
            cssSet = {'WebkitTransform' : 'translateX(' + (leftVal + value) + 'px)'};
        break
        case 'MozTransform':
            cssSet = {'MozTransform' : 'translateX(' + (leftVal + value) + 'px)'};
        break
        case 'OTransform':
            cssSet = {'OTransform' : 'translateX(' + (leftVal + value) + 'px)'};
        break
        case 'msTransform':
            cssSet = {'msTransform' : 'translateX(' + (leftVal + value) + 'px)'};
        break 
        default:
        }
        obj.css(cssSet).one('bsTransitionEnd', function(){
          ifScroll = false;
          leftVal += value;
          if (callback) {
            callback();
          }
          checkEnd();
        })
        if (navlong) {
          obj.emulateTransitionEnd(10);
        } 
        
      }else {
        obj.animate({
          "left": (leftVal + value)
        },function  () {
          ifScroll = false;
          leftVal += value;
          checkEnd();
        })
      }
    }

    //????????
    function scoll(dir,obj,moveWidth) {
      if (ifScroll == true) {
        return false;
      }
      ifScroll = true;
      if (dir=='left') {
        if (leftVal >= 0) {
          ifScroll = false;
          return false;
        }
        scrollObj(obj,opts.itemWidth);
      }

      if (dir=='right') {
        if (leftVal <= - (itemTotal-opts.parenWidth)) {
          ifScroll = false;
          return false;
        }
        scrollObj(obj,-opts.itemWidth);
      }

      if (dir == 'nav') {
        scrollObj(obj, -moveWidth,'nav');
      }
    }

    function checkEnd () {
      $this.parents("."+opts.wrapClass).find(".scroll-item-list-next").removeClass("endnext");
      $this.parents("."+opts.wrapClass).find(".scroll-item-list-prev").removeClass("endprev");

      if ($this.position().left >= 0 ) {
        $this.parents("."+opts.wrapClass).find(".scroll-item-list-prev").addClass("endprev");
        if (opts.loop = true) {
          loopRestEnd();
        }
      }
      if ($this.position().left <= - (itemTotal-opts.parenWidth) ) {
        $this.parents("."+opts.wrapClass).find(".scroll-item-list-next").addClass("endnext");

        if (opts.loop == true) {
          loopRest();
        }

      }
    }
  });
};

})(jQuery);


#T=ui-snows
///** 
* extend ???Ч??
* 
* @package jquery
* @author cuki13
  */

(function () {
    var addEvent = function (t, c, tf) {
        if (document.addEventListener) {
            document.addEventListener(t, c, tf);
        } else if (document.attachEvent) {
            document.attachEvent('on' + t, c);
        }
    }
    var app = {};
    var js_canvas_box_id = 'js_theme_christmas_2014_canvas_snow', j;
    var christmas_2014 = function () {
        function r(a) {
            return a * Math.random()
        }

        function s() {
            return document.createElement("canvas")
        }

        function t() {
            var a;
            for (var d = 0; d < m; d++)a = d < m * .6 ? 0 : d < m * .8 ? 1 : d < m * .9 ? 2 : d < m * .98 ? 3 : 4, o[d] = [r(b), r(c), a]
        }

        function u() {
            var a, d, e, f;
            p += .01, d = Math.sin(p);
            for (a = 0; a < m; a++) {
                f = o[a], e = Math.sin(4 * p + a), f[1] += f[2] / 2 + (2 + e), f[0] += 6 * (d + e / 2) / (10 / f[2]), f[1] > c && (f[1] = -n, f[0] = r(b));
                if (f[0] > b || f[0] < -n)d > 0 ? f[0] = -n : f[0] = b;
                o[a] = f
            }
        }

        function v() {
            var a;
            k.fillStyle = l, k.clearRect(0, 0, b, c), k.beginPath();
            for (a = 0; a < m; a++) {
                k.drawImage(i[o[a][2]], o[a][0], o[a][1]);
            }

            k.fill();
            u();
        }

        function w(a) {
            b = window.innerWidth,
            c = window.innerHeight,
            j !== undefined && (j.width = b, j.height = c, m = b * c / 6e3,
            l = k.createLinearGradient(0, 0, 0, c), t())
        }

        function x() {
            $(window).on('resize', function () {
                christmas_2014.resizeHandler();
            });
            j = document.createElement("canvas");

            j.style.position = "fixed";
            j.style.top = "0px";
            j.style.left = "0px";
            j.style.pointerEvents = "none";
            j.id = js_canvas_box_id;
            document.querySelector(".animate-layer").appendChild(j);

            k = j.getContext("2d");
            k.strokeStyle = "none";
            d = s(), e = s(), f = s(), g = s(), h = s(), i = [d, e, f, g, h];

            y({
                canvas: d,
                width: n * .4,
                height: n * .4,
                color: "#FFF",
                soft: .05
            });

            y({canvas: e, width: n * .5, height: n * .5, color: "#FFF", soft: .05});
            y({
                canvas: f,
                width: n * .6,
                height: n * .6,
                color: "#FFF",
                soft: .3
            });
            y({canvas: g, width: n * .8, height: n * .8, color: "#FFF", soft: .2}), y({
                canvas: h,
                width: n,
                height: n,
                color: "#FFF",
                soft: .05
            });

            w(null);

            app.snowTimer = setInterval(function () {
                q(christmas_2014.draw)
            }, 50);
        }

        function y(a) {
            var b, c, d, e, f, g, h, i, j;
            d = a.width || 30,
                e = a.height || 30,
                f = d / 2, g = e / 2,
                i = a.color || "#FFF",
                h = a.soft || 0, b = a.canvas, b.width = d, b.height = d, c = b.getContext("2d"), c.clearRect(0, 0, d, e), j = c.createRadialGradient(f, g, 0, f, g, f), j.addColorStop(0, i), j.addColorStop(.1, i), j.addColorStop(.85, z(i, h)), j.addColorStop(1, z(i, 0)), c.fillStyle = j, c.fillRect(0, 0, d, e)
        }

        function z(a, b) {
            var c, d, e;
            return a = a.replace(/^s*#|s*$/g, ""), a.length === 3 && (a = a.replace(/([0-9a-fA-F])/g, "$1$1")), d = parseInt(a.substr(2, 2), 16), e = parseInt(a.substr(4, 2), 16), c = parseInt(a.substr(0, 2), 16), "rgba(" + c + ", " + d + ", " + e + ", " + b + ")"
        }

        var b, c, d, e, f, g, h, i = [], j, k, l, m, n = 20, o = [], p = 0,
            q = function () {
                return window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame || function (a) {
                    window.setTimeout(a, 62.5)
                }
            }();
        return {
            init: x,
            draw: v,
            stop: function () {
                if (app.snowTimer) window.clearInterval(app.snowTimer);
                if(j){
                    j.parentNode.removeChild(j);
                    j = false;
                }
            },
            resizeHandler: w}
    }();

    if (!window['THEME_SCRIPT']) {
        window['THEME_SCRIPT'] = {};
    }
    window['THEME_SCRIPT'].christmas_2014 = {
        start: function () {
            if($.browser.mozilla || $.browser.webkit || ($.browser.msie && $.browser.version > 9) || window.navigator.userAgent.indexOf('rv:11') != -1){
                christmas_2014.init();
            }
        },
        stop: function () {
            if($.browser.mozilla || $.browser.webkit || ($.browser.msie && $.browser.version > 9) || window.navigator.userAgent.indexOf('rv:11') != -1){
                christmas_2014.stop();
            }
        }
    }
    christmas_2014.init();
})();
#T=ui-tag
/** 
* extend tag?л?
* 
* @package tagshow
* @author cuki13

  $('.mysp-tag').tagshow({
    objshow: $(this).find('.mysp-tagbox-section'),
    taglink: $(this).find('.mysp-taglink a'),
    current_class: 'active'
  });

*/
+(function($){  
  $.fn.tagshow = function (options) {
    var obj=$(this);

    var defualts = {
      objshow: obj.find('.c1'),     //???????? 
      taglink: obj.find('.c2 a'),     //???????
      current_class: 'current'      //????????
    };

    var opts = $.extend({}, defualts, options);  

    var is_fade=false;   //?ж?Ч??????????
    opts.taglink.click(function  (e) {
      if ($(this).hasClass(opts.current_class)) {
        return false;
      }else {
        if (is_fade) {
          return false;
        }
        var e=$(this).attr('rel');
        is_fade=true;
        
          opts.objshow.addClass('none').hide();
          $("#"+e).fadeIn(200).removeClass('none');
          is_fade=false;
        

        opts.taglink.removeClass(opts.current_class);
        $(this).addClass(opts.current_class);
      }
      return false;
    });

    
  };  
})(jQuery);
#T=ui-transition
/* ========================================================================
 * Bootstrap: transition.js v3.2.0
 * http://getbootstrap.com/javascript/#transitions
 * ========================================================================
 * Copyright 2011-2014 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 * ======================================================================== 
 $.support.transition && $parent.hasClass('fade') ?
      $parent
        .one('bsTransitionEnd', removeElement)
        .emulateTransitionEnd(150) :
removeElement()
 
 */


+function ($) {
  'use strict';

  // CSS TRANSITION SUPPORT (Shoutout: http://www.modernizr.com/)
  // ============================================================

  function transitionEnd() {
    var el = document.createElement('bootstrap')

    var transEndEventNames = {
      WebkitTransition : 'webkitTransitionEnd',
      MozTransition    : 'transitionend',
      OTransition      : 'oTransitionEnd otransitionend',
      transition       : 'transitionend'
    }

    for (var name in transEndEventNames) {
      if (el.style[name] !== undefined) {
        return { end: transEndEventNames[name] }
      }
    }

    return false // explicit for ie8 (  ._.)
  }

  // http://blog.alexmaccaw.com/css-transitions
  $.fn.emulateTransitionEnd = function (duration) {
    var called = false
    var $el = this
    $(this).one('bsTransitionEnd', function () { called = true })
    var callback = function () { if (!called) $($el).trigger($.support.transition.end) }
    setTimeout(callback, duration)
    return this
  }

  $(function () {
    $.support.transition = transitionEnd()

    if (!$.support.transition) return

    $.event.special.bsTransitionEnd = {
      bindType: $.support.transition.end,
      delegateType: $.support.transition.end,
      handle: function (e) {
        if ($(e.target).is(this)) return e.handleObj.handler.apply(this, arguments)
      }
    }
  })

}(jQuery);
#T=ul
<ul>
    <li>^!</li>
    <li></li>
</ul>
#T=unbind
unbind(^!)
#T=undelegate
undelegate(^!)
#T=unescape
unescape(^!)
#T=unload
unload(function(){
  ^!
})
#T=unshift
unshift(^!)
#T=unwrap
unwrap()^!
#T=updateSettings
updateSettings(^!)
#T=urns
urns(^!)
#T=UTC
UTC(^!)
#T=v
visibility:^!;
#T=va
vertical-align:^!;
#T=va-b
vertical-align:bottom;
#T=va-bl
vertical-align:baseline;
#T=val
val(^!)
#T=valueOf
valueOf(^!)
#T=va-m
vertical-align:middle;
#T=var
<var>^!</var>
#T=varray
var /*Array */ ^! = [];
#T=va-sub
vertical-align:sub;
#T=va-sup
vertical-align:super;
#T=va-t
vertical-align:top;
#T=va-tb
vertical-align:text-bottom;
#T=va-tt
vertical-align:text-top;
#T=v-c
visibility:collapse;
#T=vdate
var /*Date*/ 
#T=v-h
visibility:hidden;
#T=video
<video>^!</video>
#T=visible
visible
#T=vobject
var /*object*/ ^! = {};
#T=vregexp
var /*RegExp*/ ^! = new RegExp ();
#T=v-v
visibility:visible;
#T=w
width:^!;
#T=w-a
width:auto;
#T=-webkit-box-flex: 2;
-webkit-box-flex: 2;
#T=while
while (^!) {
}
#T=whs
white-space:^!;
#T=whsc
white-space-collapse:^!;
#T=whsc-ba
white-space-collapse:break-all;
#T=whsc-bs
white-space-collapse:break-strict;
#T=whsc-k
white-space-collapse:keep-all;
#T=whsc-l
white-space-collapse:loose;
#T=whsc-n
white-space-collapse:normal;
#T=whs-n
white-space:normal;
#T=whs-nw
white-space:nowrap;
#T=whs-p
white-space:pre;
#T=whs-pl
white-space:pre-line;
#T=whs-pw
white-space:pre-wrap;
#T=width()
width(^!)
#T=width=""
width="^!"
#T=with
with (^!) {
}
#T=wob
word-break:^!;
#T=wob-ba
word-break:break-all;
#T=wob-bs
word-break:break-strict;
#T=wob-k
word-break:keep-all;
#T=wob-l
word-break:loose;
#T=wob-n
word-break:normal;
#T=wos
word-spacing:^!;
#T=wow
word-wrap:^!;
#T=wow-n
word-wrap:none;
#T=wow-nm
word-wrap:normal;
#T=wow-s
word-wrap:suppress;
#T=wow-u
word-wrap:unrestricted;
#T=wrap
wrap
#T=wrap
wrap(^!)
#T=wrapAll
wrapAll(^!)
#T=wrapInner
wrapInner(^!)
#T=write
write(^!)
#T=writeln
writeln(^!)
#T=z
/*-- ^! --*/
#T=z-a
z-index:auto;
#T=zi
z-index:^!;
#T=zoo
zoom:1;

#T=zs-ze
<!-- /^! -->
#